/* app-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Orphism": { es: "Orfismo", ar: "الأورفية", zh: "奥费主义", sw: "Orfism", sv: "Orfism" },
  "A Ukrainian-French artist who explored colour in rhythmic circles across paintings, fashion and textiles.": { es: "Una artista ucraniano-francesa que exploró el color en círculos rítmicos en pinturas, moda y tejidos.", ar: "فنانة أوكرانية فرنسية استكشفت اللون في دوائر إيقاعية عبر اللوحات والأزياء والمنسوجات.", zh: "一位乌克兰裔法国艺术家，在绘画、时装和纺织品中以富有节奏的圆形探索色彩。", sw: "Msanii Mukreni-Mfaransa aliyechunguza rangi katika duara zenye mdundo kwenye michoro, mitindo ya mavazi na nguo.", sv: "En ukrainsk-fransk konstnär som utforskade färg i rytmiska cirklar i målningar, mode och textilier." },
  "Rings of contrasting colour spinning side by side echo her \"simultaneous contrasts\". In front stands an original robot drawn in the same colours, holding a laptop that fits this tool.": { es: "Anillos de colores contrastados que giran uno junto a otro evocan sus \"contrastes simultáneos\". Delante hay un robot original dibujado con los mismos colores, que sostiene un portátil acorde con esta herramienta.", ar: "حلقات من ألوان متباينة تدور جنبًا إلى جنب تحاكي \"تبايناتها المتزامنة\". وفي المقدمة يقف روبوت أصلي مرسوم بالألوان نفسها، يحمل حاسوبًا محمولًا يناسب هذه الأداة.", zh: "并排旋转的对比色圆环呼应了她的“同时对比”。前方站着一个用同样颜色画成的原创机器人，手里拿着一台与本工具相配的笔记本电脑。", sw: "Pete za rangi zinazotofautiana zikizunguka kando kwa kando zinakumbusha \"utofautishaji wake wa wakati mmoja\". Mbele amesimama roboti halisi aliyechorwa kwa rangi zilezile, akishika kompyuta mpakato inayolingana na zana hii.", sv: "Ringar i kontrasterande färger som snurrar sida vid sida påminner om hennes \"simultankontraster\". Framför står en egen robot tecknad i samma färger, med en bärbar dator som passar det här verktyget." },
  "Builds a real installable web app: a working page, a manifest, offline caching via a service worker, and app icons — download the .zip and host the files anywhere over HTTPS (GitHub Pages, Netlify, Cloudflare Pages, your own domain). Visitors can \"Add to Home Screen\" for an app-like icon.": { es: "Crea una app web real e instalable: una página que funciona, un manifiesto, caché sin conexión mediante un service worker e iconos de app. Descarga el .zip y aloja los archivos donde quieras por HTTPS (GitHub Pages, Netlify, Cloudflare Pages, tu propio dominio). Los visitantes pueden usar \"Añadir a pantalla de inicio\" para tener un icono como de app.", ar: "ينشئ تطبيق ويب حقيقيًا قابلًا للتثبيت: صفحة تعمل، وملف manifest، وتخزينًا مؤقتًا دون اتصال عبر service worker، وأيقونات للتطبيق — نزّل ملف ‎.zip واستضف الملفات في أي مكان عبر HTTPS (GitHub Pages أو Netlify أو Cloudflare Pages أو نطاقك الخاص). يمكن للزوار استخدام \"إضافة إلى الشاشة الرئيسية\" للحصول على أيقونة شبيهة بالتطبيق.", zh: "生成一个真正可安装的网页应用：可用的页面、manifest 清单、通过 service worker 实现的离线缓存以及应用图标——下载 .zip，并通过 HTTPS 将文件托管在任意位置（GitHub Pages、Netlify、Cloudflare Pages 或你自己的域名）。访客可以“添加到主屏幕”，获得类似应用的图标。", sw: "Hutengeneza programu halisi ya wavuti inayoweza kusakinishwa: ukurasa unaofanya kazi, manifest, uhifadhi wa nje ya mtandao kupitia service worker, na aikoni za programu — pakua .zip na uweke faili popote kupitia HTTPS (GitHub Pages, Netlify, Cloudflare Pages, kikoa chako mwenyewe). Wageni wanaweza \"Kuongeza kwenye Skrini ya Mwanzo\" kupata aikoni kama ya programu.", sv: "Bygger en riktig installerbar webbapp: en fungerande sida, ett manifest, offlinecache via en service worker och appikoner — ladda ner .zip-filen och lägg filerna var som helst över HTTPS (GitHub Pages, Netlify, Cloudflare Pages, din egen domän). Besökare kan välja \"Lägg till på hemskärmen\" för en appliknande ikon." },
  "⬇ Download .zip": { es: "⬇ Descargar .zip", ar: "⬇ تنزيل ‎.zip", zh: "⬇ 下载 .zip", sw: "⬇ Pakua .zip", sv: "⬇ Ladda ner .zip" },
  "Unzip and upload all the files together to any static host over HTTPS — PWAs require it. Nothing here needs a server beyond plain file hosting.": { es: "Descomprime y sube todos los archivos juntos a cualquier alojamiento estático con HTTPS; las PWA lo necesitan. Nada de esto requiere un servidor aparte del simple alojamiento de archivos.", ar: "فكّ الضغط وارفع جميع الملفات معًا إلى أي استضافة ثابتة عبر HTTPS — فتطبيقات PWA تتطلب ذلك. لا يحتاج أي شيء هنا إلى خادم سوى استضافة ملفات عادية.", zh: "解压后把所有文件一起上传到任意支持 HTTPS 的静态托管——PWA 必须使用 HTTPS。除了普通的文件托管，这里不需要任何服务器。", sw: "Fungua zip na upakie faili zote pamoja kwenye mwenyeji wowote tuli kupitia HTTPS — PWA zinahitaji hivyo. Hakuna kitu hapa kinachohitaji seva zaidi ya uhifadhi wa kawaida wa faili.", sv: "Packa upp och ladda upp alla filer tillsammans till valfritt statiskt webbhotell över HTTPS — PWA:er kräver det. Inget här behöver någon server utöver vanligt filvärdskap." },
  "Watch how App Forge works — with voice": { es: "Mira cómo funciona App Forge, con voz", ar: "شاهد كيف يعمل App Forge — مع صوت", zh: "观看 App Forge 的使用方法（带语音）", sw: "Tazama jinsi App Forge inavyofanya kazi — kwa sauti", sv: "Se hur App Forge fungerar — med röst" },
  "Welcome to App Forge. Describe an app, and get it built as an app people can install on their phone.": { es: "Bienvenido a App Forge. Describe una app y obtenla construida como una app que la gente puede instalar en su teléfono.", ar: "مرحبًا بك في App Forge. صِف تطبيقًا، واحصل عليه مبنيًا كتطبيق يمكن للناس تثبيته على هواتفهم.", zh: "欢迎使用 App Forge。描述一个应用，它就会被做成大家可以安装到手机上的应用。", sw: "Karibu App Forge. Eleza programu, na uipate ikiwa imejengwa kama programu ambayo watu wanaweza kusakinisha kwenye simu zao.", sv: "Välkommen till App Forge. Beskriv en app så byggs den som en app som folk kan installera i mobilen." },
  "Choose what you want to build. Here we make an installable web app.": { es: "Elige qué quieres crear. Aquí hacemos una app web instalable.", ar: "اختر ما تريد بناءه. هنا سنصنع تطبيق ويب قابلًا للتثبيت.", zh: "选择你想做的东西。这里我们做一个可安装的网页应用。", sw: "Chagua unachotaka kujenga. Hapa tunatengeneza programu ya wavuti inayoweza kusakinishwa.", sv: "Välj vad du vill bygga. Här gör vi en installerbar webbapp." },
  "Give it a name and describe what it should do.": { es: "Ponle un nombre y describe lo que debe hacer.", ar: "أعطه اسمًا وصِف ما يجب أن يفعله.", zh: "给它起个名字，并描述它要做什么。", sw: "Ipe jina na ueleze inapaswa kufanya nini.", sv: "Ge den ett namn och beskriv vad den ska göra." },
  "Pick a theme colour, then press Generate app.": { es: "Elige un color de tema y luego pulsa Generar app.", ar: "اختر لون السمة، ثم اضغط إنشاء التطبيق.", zh: "选一个主题色，然后按“生成应用”。", sw: "Chagua rangi ya mandhari, kisha bonyeza Tengeneza programu.", sv: "Välj en temafärg och tryck sedan på Generera app." },
  "The app runs in the preview. Try it out, and ask for changes in plain words.": { es: "La app funciona en la vista previa. Pruébala y pide cambios con palabras sencillas.", ar: "يعمل التطبيق في المعاينة. جرّبه، واطلب التغييرات بكلمات بسيطة.", zh: "应用会在预览中运行。试用一下，用平常的话提出修改要求。", sw: "Programu inafanya kazi kwenye uhakiki. Ijaribu, na uombe mabadiliko kwa maneno rahisi.", sv: "Appen körs i förhandsvisningen. Testa den och be om ändringar med vanliga ord." },
  "Download it as a zip, ready to put online or install.": { es: "Descárgala como zip, lista para publicar en línea o instalar.", ar: "نزّله كملف zip، جاهزًا للنشر على الإنترنت أو التثبيت.", zh: "把它下载为 zip，可直接上线或安装。", sw: "Ipakue kama zip, tayari kuiweka mtandaoni au kuisakinisha.", sv: "Ladda ner den som zip, redo att läggas ut på nätet eller installeras." },
  "Now it is your turn. Open App Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre App Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح App Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 App Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua App Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna App Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to App Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a App Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في App Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 App Forge。本演示使用本页上真实的工具控件。", sw: "Karibu App Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till App Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Sonia Delaunay – click for more": { es: "Arte al estilo de Sonia Delaunay: haz clic para saber más", ar: "رسم بأسلوب سونيا ديلوناي – انقر لمعرفة المزيد", zh: "索尼娅·德劳内风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Sonia Delaunay – bofya kujua zaidi", sv: "Konst i Sonia Delaunays stil – klicka för mer" },
  "e.g. A simple weekly chore tracker for a household of 4 — assign chores to people, check them off, and reset every Monday. Remember everything between visits.": { es: "p. ej. Un sencillo control semanal de tareas para un hogar de 4 personas: asigna tareas, márcalas como hechas y reinicia cada lunes. Que recuerde todo entre visitas.", ar: "مثلًا: متتبع بسيط للمهام المنزلية الأسبوعية لأسرة من 4 أفراد — وزّع المهام وضع علامة عند إنجازها وأعد الضبط كل اثنين. تذكّر كل شيء بين الزيارات.", zh: "例如：一个 4 口之家的简单每周家务表——给人分配家务、打勾完成、每周一重置。两次访问之间记住所有内容。", sw: "k.m. Kifuatiliaji rahisi cha kazi za nyumbani za kila wiki kwa familia ya watu 4 — gawa kazi kwa watu, ziwekee alama zikikamilika, na weka upya kila Jumatatu. Kumbuka kila kitu kati ya ziara.", sv: "t.ex. En enkel veckolista för hushållssysslor för 4 personer — fördela sysslor, bocka av dem och nollställ varje måndag. Kom ihåg allt mellan besöken." },
  "App preview": { es: "Vista previa de la app", ar: "معاينة التطبيق", zh: "应用预览", sw: "Uhakiki wa programu", sv: "Förhandsvisning av appen" },
  "Ask for a change, e.g. 'add a dark mode toggle'": { es: "Pide un cambio, p. ej., 'añade un interruptor de modo oscuro'", ar: "اطلب تغييرًا، مثلًا: 'أضف زر تبديل للوضع الداكن'", zh: "提出修改，例如“添加深色模式开关”", sw: "Omba badiliko, k.m. 'ongeza kitufe cha hali ya giza'", sv: "Be om en ändring, t.ex. 'lägg till en knapp för mörkt läge'" },
  "How to use App Forge": { es: "Cómo usar App Forge", ar: "كيفية استخدام App Forge", zh: "如何使用 App Forge", sw: "Jinsi ya kutumia App Forge", sv: "Så använder du App Forge" },
  "App Forge — free app generator": { es: "App Forge — generador de apps gratis", ar: "App Forge — منشئ تطبيقات مجاني", zh: "App Forge — 免费应用生成器", sw: "App Forge — kitengeneza programu cha bure", sv: "App Forge — gratis appgenerator" }
});
