/* bot-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Pop Art / street art": { es: "Arte pop / arte urbano", ar: "فن البوب / فن الشارع", zh: "波普艺术 / 街头艺术", sw: "Sanaa ya Pop / sanaa ya mitaani", sv: "Popkonst / gatukonst" },
  "An American artist whose bold outlined dancing figures began as chalk drawings in the New York subway.": { es: "Un artista estadounidense cuyas figuras danzantes de contornos marcados empezaron como dibujos con tiza en el metro de Nueva York.", ar: "فنان أمريكي بدأت شخصياته الراقصة ذات الخطوط الخارجية العريضة كرسومات بالطباشير في مترو أنفاق نيويورك.", zh: "一位美国艺术家，他那些粗线条勾勒的舞动人物最初是纽约地铁里的粉笔画。", sw: "Msanii wa Kimarekani ambaye wahusika wake wanaocheza wenye mistari mizito ya nje walianza kama michoro ya chaki katika treni ya chini ya ardhi ya New York.", sv: "En amerikansk konstnär vars kraftigt konturerade dansande figurer började som kritteckningar i New Yorks tunnelbana." },
  "Thick black-outlined dancing figures with motion lines on a bright background are his style. In front stands an original jellyfish drawn in the same colours, holding a speech bubble that fits this tool.": { es: "Figuras danzantes con gruesos contornos negros y líneas de movimiento sobre un fondo vivo son su estilo. Delante hay una medusa original dibujada con los mismos colores, que sostiene un bocadillo de diálogo acorde con esta herramienta.", ar: "شخصيات راقصة بخطوط خارجية سوداء سميكة وخطوط حركة على خلفية زاهية هي أسلوبه. وفي المقدمة يقف قنديل بحر أصلي مرسوم بالألوان نفسها، يحمل فقاعة كلام تناسب هذه الأداة.", zh: "明亮背景上带粗黑轮廓和动感线条的舞动人物，就是他的风格。前方站着一只用同样颜色画成的原创水母，手里拿着一个与本工具相配的对话气泡。", sw: "Wahusika wanaocheza wenye mistari minene myeusi ya nje na mistari ya mwendo juu ya mandharinyuma angavu ndio mtindo wake. Mbele amesimama kiwavi-bahari (jellyfish) halisi aliyechorwa kwa rangi zilezile, akishika kiputo cha maneno kinacholingana na zana hii.", sv: "Dansande figurer med tjocka svarta konturer och rörelselinjer mot en klar bakgrund är hans stil. Framför står en egen manet tecknad i samma färger, med en pratbubbla som passar det här verktyget." },
  "Your Gemini API key": { es: "Tu clave de API de Gemini", ar: "مفتاح Gemini API الخاص بك", zh: "你的 Gemini API 密钥", sw: "Ufunguo wako wa Gemini API", sv: "Din Gemini API-nyckel" },
  "Watch how Bot Forge works — with voice": { es: "Mira cómo funciona Bot Forge, con voz", ar: "شاهد كيف يعمل Bot Forge — مع صوت", zh: "观看 Bot Forge 的使用方法（带语音）", sw: "Tazama jinsi Bot Forge inavyofanya kazi — kwa sauti", sv: "Se hur Bot Forge fungerar — med röst" },
  "Welcome to Bot Forge. It makes a chat helper that answers your customers’ questions on your website.": { es: "Bienvenido a Bot Forge. Crea un asistente de chat que responde a las preguntas de tus clientes en tu sitio web.", ar: "مرحبًا بك في Bot Forge. يصنع مساعد دردشة يجيب عن أسئلة عملائك على موقعك.", zh: "欢迎使用 Bot Forge。它会制作一个聊天助手，在你的网站上回答顾客的问题。", sw: "Karibu Bot Forge. Hutengeneza msaidizi wa gumzo anayejibu maswali ya wateja wako kwenye tovuti yako.", sv: "Välkommen till Bot Forge. Den gör en chatthjälp som svarar på dina kunders frågor på din webbplats." },
  "Enter your business name and a short description.": { es: "Escribe el nombre de tu negocio y una breve descripción.", ar: "أدخل اسم نشاطك التجاري ووصفًا قصيرًا.", zh: "输入你的商号和一段简短描述。", sw: "Weka jina la biashara yako na maelezo mafupi.", sv: "Ange ditt företagsnamn och en kort beskrivning." },
  "The bot runs on your own website, so it uses your own free Gemini key. Paste it here. In this video we use a demo key.": { es: "El bot funciona en tu propio sitio web, así que usa tu propia clave gratuita de Gemini. Pégala aquí. En este vídeo usamos una clave de demostración.", ar: "يعمل الروبوت على موقعك الخاص، لذا يستخدم مفتاح Gemini المجاني الخاص بك. الصقه هنا. في هذا الفيديو نستخدم مفتاحًا تجريبيًا.", zh: "机器人运行在你自己的网站上，所以要用你自己的免费 Gemini 密钥。把它粘贴到这里。本视频中我们使用演示密钥。", sw: "Boti inafanya kazi kwenye tovuti yako mwenyewe, kwa hiyo inatumia ufunguo wako wa bure wa Gemini. Ubandike hapa. Katika video hii tunatumia ufunguo wa majaribio.", sv: "Botten körs på din egen webbplats, så den använder din egen gratis Gemini-nyckel. Klistra in den här. I den här videon använder vi en demonyckel." },
  "Now the important part: everything the bot should know, like opening hours, prices and delivery.": { es: "Ahora lo importante: todo lo que el bot debe saber, como horarios, precios y envíos.", ar: "والآن الجزء المهم: كل ما يجب أن يعرفه الروبوت، مثل ساعات العمل والأسعار والتوصيل.", zh: "现在是重点：机器人需要知道的一切，比如营业时间、价格和配送。", sw: "Sasa sehemu muhimu: kila kitu boti inapaswa kujua, kama saa za kufungua, bei na usafirishaji.", sv: "Nu det viktiga: allt som botten ska veta, som öppettider, priser och leverans." },
  "Set a welcome message and a colour, then press Build widget preview.": { es: "Define un mensaje de bienvenida y un color, y luego pulsa Crear vista previa del widget.", ar: "حدد رسالة ترحيب ولونًا، ثم اضغط إنشاء معاينة الأداة.", zh: "设置欢迎语和颜色，然后按“生成小部件预览”。", sw: "Weka ujumbe wa kukaribisha na rangi, kisha bonyeza Jenga uhakiki wa wijeti.", sv: "Ställ in ett välkomstmeddelande och en färg och tryck sedan på Bygg förhandsvisning av widgeten." },
  "Test it like a customer would. Open the chat and ask a question.": { es: "Pruébalo como lo haría un cliente. Abre el chat y haz una pregunta.", ar: "اختبره كما يفعل العميل. افتح الدردشة واطرح سؤالًا.", zh: "像顾客一样测试它。打开聊天窗口并提一个问题。", sw: "Ijaribu kama mteja angefanya. Fungua gumzo na uulize swali.", sv: "Testa den som en kund skulle göra. Öppna chatten och ställ en fråga." },
  "The bot answers from your information only. When you are happy, copy the embed code into your website.": { es: "El bot responde solo con tu información. Cuando estés satisfecho, copia el código para insertar en tu sitio web.", ar: "يجيب الروبوت من معلوماتك فقط. عندما تكون راضيًا، انسخ رمز التضمين إلى موقعك.", zh: "机器人只根据你提供的信息回答。满意后，把嵌入代码复制到你的网站里。", sw: "Boti hujibu kutoka kwa taarifa zako pekee. Ukiridhika, nakili msimbo wa kupachika kwenye tovuti yako.", sv: "Botten svarar bara utifrån din information. När du är nöjd kopierar du inbäddningskoden till din webbplats." },
  "Now it is your turn. Open Bot Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Bot Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Bot Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Bot Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Bot Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Bot Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Bot Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Bot Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Bot Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Bot Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Bot Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Bot Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Keith Haring – click for more": { es: "Arte al estilo de Keith Haring: haz clic para saber más", ar: "رسم بأسلوب كيث هارينغ – انقر لمعرفة المزيد", zh: "凯斯·哈林风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Keith Haring – bofya kujua zaidi", sv: "Konst i Keith Harings stil – klicka för mer" },
  "e.g. A family-owned plumbing company serving Austin, TX since 2005.": { es: "p. ej. Una empresa familiar de fontanería que da servicio en Austin, TX, desde 2005.", ar: "مثلًا: شركة سباكة عائلية تخدم أوستن، تكساس منذ 2005.", zh: "例如：一家自 2005 年起服务于得州奥斯汀的家族水管公司。", sw: "k.m. Kampuni ya familia ya mabomba inayohudumia Austin, TX tangu 2005.", sv: "t.ex. Ett familjeägt rörfirma som har servat Austin, TX sedan 2005." },
  "e.g. We're open Mon-Fri 8am-6pm. Emergency call-outs are $150. We service Austin and surrounding areas within 30 miles. We do NOT work on commercial properties.": { es: "p. ej. Abrimos de lunes a viernes de 8:00 a 18:00. Las urgencias cuestan 150 $. Damos servicio en Austin y alrededores en un radio de 30 millas. NO trabajamos en locales comerciales.", ar: "مثلًا: نعمل من الاثنين إلى الجمعة 8 ص–6 م. زيارات الطوارئ بـ150 دولارًا. نخدم أوستن والمناطق المحيطة ضمن 30 ميلًا. لا نعمل في العقارات التجارية.", zh: "例如：我们周一至周五早 8 点到晚 6 点营业。紧急上门费 150 美元。服务奥斯汀及周边 30 英里范围。我们不承接商业物业。", sw: "k.m. Tuko wazi Jumatatu–Ijumaa saa 2 asubuhi–saa 12 jioni. Huduma za dharura ni $150. Tunahudumia Austin na maeneo jirani ndani ya maili 30. HATUFANYI kazi kwenye majengo ya biashara.", sv: "t.ex. Vi har öppet mån–fre 8–18. Akututryckning kostar 150 $. Vi servar Austin med omnejd inom 30 miles. Vi arbetar INTE med kommersiella fastigheter." },
  "How to use Bot Forge": { es: "Cómo usar Bot Forge", ar: "كيفية استخدام Bot Forge", zh: "如何使用 Bot Forge", sw: "Jinsi ya kutumia Bot Forge", sv: "Så använder du Bot Forge" },
  "Bot Forge — free website chat & FAQ widget generator": { es: "Bot Forge — generador gratis de widgets de chat y preguntas frecuentes para webs", ar: "Bot Forge — منشئ مجاني لأدوات الدردشة والأسئلة الشائعة للمواقع", zh: "Bot Forge — 免费的网站聊天和常见问题小部件生成器", sw: "Bot Forge — kitengeneza wijeti za gumzo na maswali ya mara kwa mara kwa tovuti, cha bure", sv: "Bot Forge — gratis generator för chatt- och FAQ-widgetar till webbplatser" }
});
