/* contract-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Early Netherlandish painting": { es: "Pintura flamenca primitiva", ar: "الرسم الهولندي المبكر", zh: "早期尼德兰绘画", sw: "Uchoraji wa mapema wa Uholanzi", sv: "Tidig nederländsk måleri" },
  "A Flemish master who perfected oil painting, reaching jewel-like detail in works such as the Ghent Altarpiece and the Arnolfini Portrait.": { es: "Un maestro flamenco que perfeccionó la pintura al óleo y alcanzó un detalle de joyero en obras como el Políptico de Gante y el Retrato de los Arnolfini.", ar: "معلّم فلمنكي أتقن الرسم الزيتي، وبلغ دقة تشبه دقة المجوهرات في أعمال مثل \"مذبح غنت\" و\"بورتريه أرنولفيني\".", zh: "一位佛兰德斯大师，完善了油画技法，在《根特祭坛画》和《阿尔诺芬尼夫妇像》等作品中达到珠宝般精细的程度。", sw: "Gwiji wa Kiflemi aliyeboresha uchoraji wa rangi za mafuta, akifikia undani kama wa vito katika kazi kama Ghent Altarpiece na Arnolfini Portrait.", sv: "En flamländsk mästare som fulländade oljemåleriet och nådde juvelliknande detaljrikedom i verk som Gentaltaret och Arnolfinis bröllop." },
  "The round convex mirror with its ring of small gold beads nods to the famous mirror in the Arnolfini Portrait, set in a dark green interior. In front stands an original owl drawn in the same colours, holding a scroll that fits this tool.": { es: "El espejo redondo y convexo con su anillo de pequeñas cuentas doradas alude al famoso espejo del Retrato de los Arnolfini, en un interior verde oscuro. Delante hay un búho original dibujado con los mismos colores, que sostiene un pergamino acorde con esta herramienta.", ar: "المرآة المحدّبة المستديرة بحلقتها من الخرزات الذهبية الصغيرة تشير إلى المرآة الشهيرة في \"بورتريه أرنولفيني\"، في داخل غرفة خضراء داكنة. وفي المقدمة تقف بومة أصلية مرسومة بالألوان نفسها، تحمل لفافة تناسب هذه الأداة.", zh: "深绿色室内的那面圆形凸面镜，镜框上环绕着小金珠，致敬了《阿尔诺芬尼夫妇像》中的著名镜子。前方站着一只用同样颜色画成的原创猫头鹰，手里拿着一卷与本工具相配的卷轴。", sw: "Kioo cha mviringo kilichobonyea nje chenye pete ya shanga ndogo za dhahabu kinadokeza kioo maarufu katika Arnolfini Portrait, ndani ya chumba cha kijani kilichokolea. Mbele amesimama bundi halisi aliyechorwa kwa rangi zilezile, akishika hati ya kukunja inayolingana na zana hii.", sv: "Den runda konvexa spegeln med sin ring av små guldpärlor blinkar åt den berömda spegeln i Arnolfinis bröllop, i en mörkgrön interiör. Framför står en egen uggla tecknad i samma färger, med en skriftrulle som passar det här verktyget." },
  "Watch how Contract Forge works — with voice": { es: "Mira cómo funciona Contract Forge, con voz", ar: "شاهد كيف يعمل Contract Forge — مع صوت", zh: "观看 Contract Forge 的使用方法（带语音）", sw: "Tazama jinsi Contract Forge inavyofanya kazi — kwa sauti", sv: "Se hur Contract Forge fungerar — med röst" },
  "Welcome to Contract Forge. It helps you draft a clear, simple agreement.": { es: "Bienvenido a Contract Forge. Te ayuda a redactar un acuerdo claro y sencillo.", ar: "مرحبًا بك في Contract Forge. يساعدك على صياغة اتفاقية واضحة وبسيطة.", zh: "欢迎使用 Contract Forge。它帮你起草一份清晰、简单的协议。", sw: "Karibu Contract Forge. Inakusaidia kuandaa makubaliano yaliyo wazi na rahisi.", sv: "Välkommen till Contract Forge. Den hjälper dig att skriva ett tydligt och enkelt avtal." },
  "Enter your business name, choose the type of contract, and add the other party.": { es: "Escribe el nombre de tu negocio, elige el tipo de contrato y añade a la otra parte.", ar: "أدخل اسم نشاطك التجاري، واختر نوع العقد، وأضف الطرف الآخر.", zh: "输入你的商号，选择合同类型，并添加另一方。", sw: "Weka jina la biashara yako, chagua aina ya mkataba, na uongeze upande mwingine.", sv: "Ange ditt företagsnamn, välj typ av avtal och lägg till motparten." },
  "Describe the work and the payment terms in plain words.": { es: "Describe el trabajo y las condiciones de pago con palabras sencillas.", ar: "صِف العمل وشروط الدفع بكلمات بسيطة.", zh: "用平实的语言描述工作内容和付款条件。", sw: "Eleza kazi na masharti ya malipo kwa maneno rahisi.", sv: "Beskriv arbetet och betalningsvillkoren med enkla ord." },
  "The contract preview fills in as you type. Both people can even sign on screen.": { es: "La vista previa del contrato se completa mientras escribes. Ambas personas pueden incluso firmar en pantalla.", ar: "تمتلئ معاينة العقد أثناء الكتابة. ويمكن للطرفين حتى التوقيع على الشاشة.", zh: "合同预览会随着输入自动填充。双方甚至可以直接在屏幕上签名。", sw: "Uhakiki wa mkataba hujazwa unapoandika. Watu wote wawili wanaweza hata kusaini kwenye skrini.", sv: "Förhandsvisningen av avtalet fylls i medan du skriver. Båda parter kan till och med skriva under på skärmen." },
  "Always read every clause carefully. Then print it or download it.": { es: "Lee siempre cada cláusula con atención. Luego imprímelo o descárgalo.", ar: "اقرأ كل بند بعناية دائمًا. ثم اطبعه أو نزّله.", zh: "务必仔细阅读每一条条款。然后打印或下载。", sw: "Soma kila kifungu kwa makini kila wakati. Kisha uuchapishe au uupakue.", sv: "Läs alltid varje klausul noga. Skriv sedan ut det eller ladda ner det." },
  "Now it is your turn. Open Contract Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Contract Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Contract Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Contract Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Contract Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Contract Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Contract Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Contract Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Contract Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Contract Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Contract Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Contract Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Jan van Eyck – click for more": { es: "Arte al estilo de Jan van Eyck: haz clic para saber más", ar: "رسم بأسلوب يان فان آيك – انقر لمعرفة المزيد", zh: "扬·凡·艾克风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Jan van Eyck – bofya kujua zaidi", sv: "Konst i Jan van Eycks stil – klicka för mer" },
  "Your Business": { es: "Tu negocio", ar: "نشاطك التجاري", zh: "你的公司", sw: "Biashara Yako", sv: "Ditt företag" },
  "Client or contractor name": { es: "Nombre del cliente o contratista", ar: "اسم العميل أو المتعاقد", zh: "客户或承包方名称", sw: "Jina la mteja au mkandarasi", sv: "Kundens eller uppdragstagarens namn" },
  "Defaults to today if left blank": { es: "Si lo dejas vacío, se usa la fecha de hoy", ar: "يُستخدم تاريخ اليوم إذا تُرك فارغًا", zh: "留空则默认为今天", sw: "Ikiachwa tupu, tarehe ya leo hutumika", sv: "Dagens datum används om fältet lämnas tomt" },
  "e.g. Weekly lawn mowing and hedge trimming at 123 Main St, April–October": { es: "p. ej. Corte de césped y poda de setos semanales en 123 Main St, de abril a octubre", ar: "مثلًا: قص العشب وتشذيب السياج أسبوعيًا في 123 Main St، من أبريل إلى أكتوبر", zh: "例如：4 月至 10 月每周在 123 Main St 修剪草坪和树篱", sw: "k.m. Kukata nyasi na kupunguza ua kila wiki katika 123 Main St, Aprili–Oktoba", sv: "t.ex. Gräsklippning och häckklippning varje vecka på 123 Main St, april–oktober" },
  "e.g. $150/visit, due within 7 days of service. Either party may cancel with 14 days' written notice.": { es: "p. ej. 150 $/visita, a pagar en los 7 días siguientes al servicio. Cualquiera de las partes puede cancelar con 14 días de preaviso por escrito.", ar: "مثلًا: 150 دولارًا للزيارة، تُستحق خلال 7 أيام من الخدمة. يجوز لأي طرف الإلغاء بإشعار كتابي قبل 14 يومًا.", zh: "例如：每次 150 美元，服务后 7 天内付清。任何一方均可提前 14 天书面通知解约。", sw: "k.m. $150/ziara, inalipwa ndani ya siku 7 baada ya huduma. Upande wowote unaweza kusitisha kwa notisi ya maandishi ya siku 14.", sv: "t.ex. 150 $/besök, förfaller inom 7 dagar efter utfört arbete. Båda parter kan säga upp med 14 dagars skriftligt varsel." },
  "e.g. State of Texas": { es: "p. ej., Estado de Texas", ar: "مثلًا: ولاية تكساس", zh: "例如：得克萨斯州", sw: "k.m. Jimbo la Texas", sv: "t.ex. delstaten Texas" },
  "Document preview": { es: "Vista previa del documento", ar: "معاينة المستند", zh: "文档预览", sw: "Uhakiki wa hati", sv: "Förhandsvisning av dokumentet" },
  "How to use Contract Forge": { es: "Cómo usar Contract Forge", ar: "كيفية استخدام Contract Forge", zh: "如何使用 Contract Forge", sw: "Jinsi ya kutumia Contract Forge", sv: "Så använder du Contract Forge" },
  "Contract Forge — free contract & NDA generator": { es: "Contract Forge — generador de contratos y acuerdos de confidencialidad gratis", ar: "Contract Forge — منشئ عقود واتفاقيات عدم إفصاح مجاني", zh: "Contract Forge — 免费合同和保密协议生成器", sw: "Contract Forge — kitengeneza mikataba na NDA cha bure", sv: "Contract Forge — gratis generator för avtal och sekretessavtal" }
});
