/* feedback.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Feedback & Suggestions": { es: "Comentarios y sugerencias", ar: "الملاحظات والاقتراحات", zh: "反馈与建议", sw: "Maoni na Mapendekezo", sv: "Feedback och förslag" },
  "Expressionism": { es: "Expresionismo", ar: "التعبيرية", zh: "表现主义", sw: "Uelezaji", sv: "Expressionism" },
  "A Norwegian painter of anxiety and emotion, known worldwide for The Scream.": { es: "Un pintor noruego de la angustia y la emoción, conocido en todo el mundo por El grito.", ar: "رسام نرويجي للقلق والعاطفة، معروف عالميًا بلوحة \"الصرخة\".", zh: "一位描绘焦虑与情感的挪威画家，以《呐喊》闻名世界。", sw: "Mchoraji wa Kinorwe wa wasiwasi na hisia, anayejulikana duniani kote kwa The Scream.", sv: "En norsk målare av ångest och känslor, världskänd för Skriet." },
  "Wavy bands of blood-orange sky over dark blue water and a diagonal bridge rail come from The Scream. In front stands an original ghost drawn in the same colours, holding a speech bubble that fits this tool.": { es: "Las franjas onduladas de cielo naranja sangre sobre agua azul oscuro y la barandilla diagonal del puente vienen de El grito. Delante hay un fantasma original dibujado con los mismos colores, que sostiene un bocadillo de diálogo acorde con esta herramienta.", ar: "أشرطة متموجة من سماء برتقالية بلون الدم فوق مياه زرقاء داكنة ودرابزين جسر مائل مستوحاة من \"الصرخة\". وفي المقدمة يقف شبح أصلي مرسوم بالألوان نفسها، يحمل فقاعة كلام تناسب هذه الأداة.", zh: "深蓝水面上方血橙色天空的波浪色带，以及斜穿画面的桥栏，都出自《呐喊》。前方站着一个用同样颜色画成的原创幽灵，手里拿着一个与本工具相配的对话气泡。", sw: "Mikanda inayopinda ya anga la rangi ya chungwa-damu juu ya maji ya bluu iliyokolea na reli ya daraja ya mshazari vinatoka The Scream. Mbele amesimama mzimu halisi aliyechorwa kwa rangi zilezile, akishika kiputo cha maneno kinacholingana na zana hii.", sv: "Vågiga band av blodorange himmel över mörkblått vatten och ett diagonalt broräcke kommer från Skriet. Framför står ett eget spöke tecknat i samma färger, med en pratbubbla som passar det här verktyget." },
  "Leave this field blank": { es: "Deja este campo vacío", ar: "اترك هذا الحقل فارغًا", zh: "此栏请留空", sw: "Acha sehemu hii tupu", sv: "Lämna det här fältet tomt" },
  "Art in the style of Edvard Munch – click for more": { es: "Arte al estilo de Edvard Munch: haz clic para saber más", ar: "رسم بأسلوب إدفارد مونك – انقر لمعرفة المزيد", zh: "爱德华·蒙克风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Edvard Munch – bofya kujua zaidi", sv: "Konst i Edvard Munchs stil – klicka för mer" },
  "e.g. Add a way to reorder sound clips": { es: "p. ej., Añadir una forma de reordenar los clips de sonido", ar: "مثلًا: أضف طريقة لإعادة ترتيب المقاطع الصوتية", zh: "例如：添加一种重新排列音频片段的方式", sw: "k.m. Ongeza njia ya kupanga upya klipu za sauti", sv: "t.ex. Lägg till ett sätt att ändra ordning på ljudklipp" },
  "What happened, or what you'd like to see? The more specific, the easier it is to act on.": { es: "¿Qué pasó o qué te gustaría ver? Cuanto más concreto, más fácil será actuar.", ar: "ماذا حدث، أو ما الذي تودّ رؤيته؟ كلما كنت أدق كان التصرف أسهل.", zh: "发生了什么，或者你希望看到什么？越具体，越容易处理。", sw: "Nini kilitokea, au ungependa kuona nini? Kadiri ulivyo mahususi zaidi, ndivyo inavyokuwa rahisi kuchukua hatua.", sv: "Vad hände, eller vad vill du se? Ju mer konkret, desto lättare att göra något åt det." },
  "Anyone can read this on GitHub; leave blank to stay anonymous": { es: "Cualquiera puede leer esto en GitHub; déjalo vacío para seguir en el anonimato", ar: "يمكن لأي شخص قراءة هذا على GitHub؛ اتركه فارغًا لتبقى مجهول الهوية", zh: "任何人都能在 GitHub 上看到这些内容；留空即可保持匿名", sw: "Mtu yeyote anaweza kusoma hili kwenye GitHub; acha tupu ili ubaki bila kujulikana", sv: "Vem som helst kan läsa det här på GitHub; lämna tomt för att vara anonym" }
});
