/* file-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Impressionism": { es: "Impresionismo", ar: "الانطباعية", zh: "印象派", sw: "Uimpresionisti", sv: "Impressionism" },
  "A founder of French Impressionism, who painted the same scenes again and again to catch changing light, above all his water lilies at Giverny.": { es: "Uno de los fundadores del impresionismo francés, que pintó las mismas escenas una y otra vez para captar la luz cambiante, sobre todo sus nenúfares de Giverny.", ar: "أحد مؤسسي الانطباعية الفرنسية، رسم المشاهد نفسها مرارًا وتكرارًا ليلتقط الضوء المتغير، وأشهرها زنابق الماء في جيفرني.", zh: "法国印象派的创始人之一，一遍又一遍地描绘同一场景以捕捉变幻的光线，最著名的是他在吉维尼画的睡莲。", sw: "Mmoja wa waanzilishi wa Uimpresionisti wa Kifaransa, aliyechora mandhari zilezile tena na tena ili kunasa mwanga unaobadilika, hasa yungiyungi zake za maji huko Giverny.", sv: "En av grundarna av den franska impressionismen, som målade samma motiv om och om igen för att fånga det skiftande ljuset, framför allt näckrosorna i Giverny." },
  "Short dabs of blue and green on water with floating lily pads are his Water Lilies. In front stands an original frog drawn in the same colours, holding a camera that fits this tool.": { es: "Pequeños toques de azul y verde sobre el agua con hojas de nenúfar flotando son sus Nenúfares. Delante hay una rana original dibujada con los mismos colores, que sostiene una cámara acorde con esta herramienta.", ar: "لمسات قصيرة من الأزرق والأخضر على الماء مع أوراق زنابق طافية هي لوحاته \"زنابق الماء\". وفي المقدمة يقف ضفدع أصلي مرسوم بالألوان نفسها، يحمل كاميرا تناسب هذه الأداة.", zh: "水面上短促的蓝绿色笔触和漂浮的睡莲叶，就是他的《睡莲》。前方站着一只用同样颜色画成的原创青蛙，手里拿着一台与本工具相配的相机。", sw: "Madoa mafupi ya bluu na kijani juu ya maji pamoja na majani ya yungiyungi yanayoelea ndiyo Water Lilies zake. Mbele amesimama chura halisi aliyechorwa kwa rangi zilezile, akishika kamera inayolingana na zana hii.", sv: "Korta duttar av blått och grönt på vatten med flytande näckrosblad är hans Näckrosor. Framför står en egen groda tecknad i samma färger, med en kamera som passar det här verktyget." },
  "Re-exporting removes embedded camera and location metadata. Processing stays on this device.": { es: "Al volver a exportar se eliminan los metadatos de cámara y ubicación incrustados. El procesamiento se queda en este dispositivo.", ar: "تؤدي إعادة التصدير إلى إزالة بيانات الكاميرا والموقع الوصفية المضمّنة. وتبقى المعالجة على هذا الجهاز.", zh: "重新导出会移除内嵌的相机和位置元数据。处理全程在本设备上进行。", sw: "Kuhamisha upya huondoa metadata iliyopachikwa ya kamera na mahali. Uchakataji unabaki kwenye kifaa hiki.", sv: "Vid omexport tas inbäddad kamera- och platsmetadata bort. Bearbetningen sker på den här enheten." },
  "Watch how File Forge works — with voice": { es: "Mira cómo funciona File Forge, con voz", ar: "شاهد كيف يعمل File Forge — مع صوت", zh: "观看 File Forge 的使用方法（带语音）", sw: "Tazama jinsi File Forge inavyofanya kazi — kwa sauti", sv: "Se hur File Forge fungerar — med röst" },
  "Welcome to Image Forge. Convert, resize and compress many images at once, privately.": { es: "Bienvenido a Image Forge. Convierte, redimensiona y comprime muchas imágenes a la vez, de forma privada.", ar: "مرحبًا بك في Image Forge. حوّل صورًا كثيرة وغيّر حجمها واضغطها دفعة واحدة، بخصوصية.", zh: "欢迎使用 Image Forge。私密地一次性转换、缩放和压缩多张图片。", sw: "Karibu Image Forge. Geuza, badilisha ukubwa na ubane picha nyingi kwa wakati mmoja, kwa faragha.", sv: "Välkommen till Image Forge. Konvertera, ändra storlek på och komprimera många bilder samtidigt, privat." },
  "Choose your images, or drag them onto the page. Here is a large landscape photo.": { es: "Elige tus imágenes o arrástralas a la página. Aquí hay una foto de paisaje grande.", ar: "اختر صورك، أو اسحبها إلى الصفحة. هذه صورة منظر طبيعي كبيرة.", zh: "选择你的图片，或把它们拖到页面上。这里是一张大尺寸风景照。", sw: "Chagua picha zako, au uziburute kwenye ukurasa. Hii hapa ni picha kubwa ya mandhari.", sv: "Välj dina bilder eller dra dem till sidan. Här är ett stort landskapsfoto." },
  "Pick the new format. WebP makes much smaller files for websites.": { es: "Elige el nuevo formato. WebP genera archivos mucho más pequeños para webs.", ar: "اختر الصيغة الجديدة. صيغة WebP تُنتج ملفات أصغر بكثير للمواقع.", zh: "选择新格式。WebP 能为网站生成小得多的文件。", sw: "Chagua muundo mpya. WebP hutengeneza faili ndogo zaidi kwa tovuti.", sv: "Välj det nya formatet. WebP ger mycket mindre filer för webbplatser." },
  "Set the quality, and a maximum size if you want to shrink the image.": { es: "Ajusta la calidad y un tamaño máximo si quieres reducir la imagen.", ar: "اضبط الجودة، وحدًا أقصى للحجم إن أردت تصغير الصورة.", zh: "设置画质；如果想缩小图片，再设置最大尺寸。", sw: "Weka ubora, na ukubwa wa juu kabisa ukitaka kupunguza picha.", sv: "Ställ in kvaliteten och en maxstorlek om du vill krympa bilden." },
  "Press Convert and download. Location data and other hidden details are removed too.": { es: "Pulsa Convertir y descargar. También se eliminan los datos de ubicación y otros detalles ocultos.", ar: "اضغط تحويل وتنزيل. تُزال أيضًا بيانات الموقع وغيرها من التفاصيل المخفية.", zh: "按“转换并下载”。位置数据和其他隐藏信息也会被移除。", sw: "Bonyeza Geuza na upakue. Data ya mahali na maelezo mengine yaliyofichwa pia huondolewa.", sv: "Tryck på Konvertera och ladda ner. Platsdata och andra dolda uppgifter tas också bort." },
  "Now it is your turn. Open Image Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Image Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Image Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Image Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Image Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Image Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to File Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a File Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في File Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 File Forge。本演示使用本页上真实的工具控件。", sw: "Karibu File Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till File Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Claude Monet – click for more": { es: "Arte al estilo de Claude Monet: haz clic para saber más", ar: "رسم بأسلوب كلود مونيه – انقر لمعرفة المزيد", zh: "克劳德·莫奈风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Claude Monet – bofya kujua zaidi", sv: "Konst i Claude Monets stil – klicka för mer" },
  "How to use File Forge": { es: "Cómo usar File Forge", ar: "كيفية استخدام File Forge", zh: "如何使用 File Forge", sw: "Jinsi ya kutumia File Forge", sv: "Så använder du File Forge" },
  "Image Forge — private batch image converter": { es: "Image Forge — conversor privado de imágenes por lotes", ar: "Image Forge — محوّل صور خاص للدفعات", zh: "Image Forge — 私密的批量图片转换器", sw: "Image Forge — kigeuzi cha faragha cha picha kwa makundi", sv: "Image Forge — privat batchkonverterare för bilder" }
});
