/* invoice-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Rococo veduta (view painting)": { es: "Veduta rococó (pintura de vistas)", ar: "الفيدوتا الروكوكو (رسم المناظر)", zh: "洛可可风景画（城市景观画）", sw: "Veduta ya Rokoko (uchoraji wa mandhari)", sv: "Rokokoveduta (vymålning)" },
  "A Venetian painter of detailed, sunlit city views of the Grand Canal and its palaces.": { es: "Un pintor veneciano de vistas urbanas detalladas y soleadas del Gran Canal y sus palacios.", ar: "رسام من البندقية اشتهر بمناظر مدينة مفصّلة ومشمسة للقناة الكبرى وقصورها.", zh: "一位威尼斯画家，以描绘大运河及其宫殿的细致、阳光明媚的城市风景闻名。", sw: "Mchoraji wa Venisi wa mandhari ya mji yenye undani na jua ya Mfereji Mkuu na majumba yake.", sv: "En venetiansk målare av detaljerade, solbelysta stadsvyer över Canal Grande och dess palats." },
  "A row of pastel palaces with little windows above blue canal water and a gondola recalls his views of Venice. In front stands an original troll drawn in the same colours, holding a pile of coins that fits this tool.": { es: "Una hilera de palacios pastel con ventanitas sobre el agua azul del canal y una góndola recuerda sus vistas de Venecia. Delante hay un trol original dibujado con los mismos colores, que sostiene un montón de monedas acorde con esta herramienta.", ar: "صف من القصور بألوان الباستيل ذات نوافذ صغيرة فوق مياه القناة الزرقاء وجندول يذكّر بمناظره للبندقية. وفي المقدمة يقف قزم ترول أصلي مرسوم بالألوان نفسها، يحمل كومة من العملات تناسب هذه الأداة.", zh: "蓝色运河水面上方一排带小窗的粉彩宫殿和一艘贡多拉，让人想起他笔下的威尼斯风景。前方站着一个用同样颜色画成的原创巨魔，手里拿着一堆与本工具相配的硬币。", sw: "Safu ya majumba ya rangi hafifu yenye madirisha madogo juu ya maji ya bluu ya mfereji na gondola inakumbusha mandhari zake za Venisi. Mbele amesimama zimwi halisi aliyechorwa kwa rangi zilezile, akishika rundo la sarafu linalolingana na zana hii.", sv: "En rad pastellfärgade palats med små fönster ovanför blått kanalvatten och en gondol påminner om hans vyer över Venedig. Framför står ett eget troll tecknat i samma färger, med en hög mynt som passar det här verktyget." },
  "Watch how Invoice Forge works — with voice": { es: "Mira cómo funciona Invoice Forge, con voz", ar: "شاهد كيف يعمل Invoice Forge — مع صوت", zh: "观看 Invoice Forge 的使用方法（带语音）", sw: "Tazama jinsi Invoice Forge inavyofanya kazi — kwa sauti", sv: "Se hur Invoice Forge fungerar — med röst" },
  "Welcome to Invoice Forge. Let us make a professional invoice in about a minute.": { es: "Bienvenido a Invoice Forge. Vamos a crear una factura profesional en un minuto más o menos.", ar: "مرحبًا بك في Invoice Forge. لنصنع فاتورة احترافية في دقيقة تقريبًا.", zh: "欢迎使用 Invoice Forge。我们用大约一分钟做一张专业发票。", sw: "Karibu Invoice Forge. Hebu tutengeneze ankara ya kitaalamu kwa takriban dakika moja.", sv: "Välkommen till Invoice Forge. Vi gör en professionell faktura på ungefär en minut." },
  "Enter your business name and your client’s name.": { es: "Escribe el nombre de tu negocio y el de tu cliente.", ar: "أدخل اسم نشاطك التجاري واسم عميلك.", zh: "输入你的商号和客户的名称。", sw: "Weka jina la biashara yako na jina la mteja wako.", sv: "Ange ditt företagsnamn och din kunds namn." },
  "Choose whether this is a quote or an invoice.": { es: "Elige si es un presupuesto o una factura.", ar: "اختر ما إذا كان هذا عرض سعر أم فاتورة.", zh: "选择这是报价单还是发票。", sw: "Chagua kama hii ni nukuu ya bei au ankara.", sv: "Välj om det är en offert eller en faktura." },
  "Add each line item with a quantity and price. The totals are calculated for you.": { es: "Añade cada concepto con su cantidad y precio. Los totales se calculan por ti.", ar: "أضف كل بند مع الكمية والسعر. تُحسب المجاميع تلقائيًا.", zh: "逐项添加明细，填写数量和单价。合计会自动算好。", sw: "Ongeza kila kipengele pamoja na idadi na bei. Jumla hukokotolewa kwa ajili yako.", sv: "Lägg till varje rad med antal och pris. Summorna räknas ut åt dig." },
  "Add a discount or tax rate if you need one. The preview updates as you type.": { es: "Añade un descuento o un tipo de impuesto si lo necesitas. La vista previa se actualiza mientras escribes.", ar: "أضف خصمًا أو نسبة ضريبة إن احتجت. تتحدث المعاينة أثناء الكتابة.", zh: "如有需要，可添加折扣或税率。预览会随输入实时更新。", sw: "Ongeza punguzo au kiwango cha kodi ukihitaji. Uhakiki husasishwa unapoandika.", sv: "Lägg till rabatt eller momssats om du behöver. Förhandsvisningen uppdateras medan du skriver." },
  "When it looks right, print it, save it as a PDF, or download it.": { es: "Cuando esté bien, imprímela, guárdala como PDF o descárgala.", ar: "عندما تبدو صحيحة، اطبعها أو احفظها بصيغة PDF أو نزّلها.", zh: "确认无误后，打印、另存为 PDF 或下载。", sw: "Ikionekana sawa, ichapishe, ihifadhi kama PDF, au uipakue.", sv: "När den ser rätt ut skriver du ut den, sparar den som PDF eller laddar ner den." },
  "Now it is your turn. Open Invoice Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Invoice Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Invoice Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Invoice Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Invoice Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Invoice Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Invoice Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Invoice Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Invoice Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Invoice Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Invoice Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Invoice Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Canaletto – click for more": { es: "Arte al estilo de Canaletto: haz clic para saber más", ar: "رسم بأسلوب كاناليتو – انقر لمعرفة المزيد", zh: "卡纳莱托风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Canaletto – bofya kujua zaidi", sv: "Konst i Canalettos stil – klicka för mer" },
  "Your Business": { es: "Tu negocio", ar: "نشاطك التجاري", zh: "你的公司", sw: "Biashara Yako", sv: "Ditt företag" },
  "Who this is for": { es: "Para quién es", ar: "لمن هذا", zh: "开给谁", sw: "Hii ni ya nani", sv: "Vem den är till" },
  "Client's address": { es: "Dirección del cliente", ar: "عنوان العميل", zh: "客户地址", sw: "Anwani ya mteja", sv: "Kundens adress" },
  "Description": { es: "Descripción", ar: "الوصف", zh: "描述", sw: "Maelezo", sv: "Beskrivning" },
  "Remove": { es: "Eliminar", ar: "إزالة", zh: "删除", sw: "Ondoa", sv: "Ta bort" },
  "Document preview": { es: "Vista previa del documento", ar: "معاينة المستند", zh: "文档预览", sw: "Uhakiki wa hati", sv: "Förhandsvisning av dokumentet" },
  "How to use Invoice Forge": { es: "Cómo usar Invoice Forge", ar: "كيفية استخدام Invoice Forge", zh: "如何使用 Invoice Forge", sw: "Jinsi ya kutumia Invoice Forge", sv: "Så använder du Invoice Forge" },
  "Invoice Forge — free quote & invoice generator": { es: "Invoice Forge — generador de presupuestos y facturas gratis", ar: "Invoice Forge — منشئ عروض أسعار وفواتير مجاني", zh: "Invoice Forge — 免费报价单和发票生成器", sw: "Invoice Forge — kitengeneza nukuu za bei na ankara cha bure", sv: "Invoice Forge — gratis generator för offerter och fakturor" }
});
