/* logo-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Art Deco": { es: "Art déco", ar: "آرت ديكو", zh: "装饰艺术", sw: "Art Deco", sv: "Art déco" },
  "A Polish painter of glamorous, polished portraits in the style of 1920s Art Deco.": { es: "Una pintora polaca de retratos glamurosos y pulidos al estilo art déco de los años veinte.", ar: "رسامة بولندية اشتهرت بالبورتريهات الفاخرة المصقولة على طراز آرت ديكو في عشرينيات القرن العشرين.", zh: "一位波兰画家，以 1920 年代装饰艺术风格的华丽、精致肖像闻名。", sw: "Mchoraji wa Kipolandi wa picha za watu za kupendeza na zilizong'arishwa kwa mtindo wa Art Deco wa miaka ya 1920.", sv: "En polsk målare av glamorösa, polerade porträtt i 1920-talets art déco-stil." },
  "Metallic grey pillars and a sweep of glossy red fabric echo her smooth, sculpted Art Deco look. In front stands an original gremlin drawn in the same colours, holding a star that fits this tool.": { es: "Columnas gris metálico y un vuelo de tela roja brillante evocan su estética art déco, lisa y escultural. Delante hay un gremlin original dibujado con los mismos colores, que sostiene una estrella acorde con esta herramienta.", ar: "أعمدة رمادية معدنية وانسياب قماش أحمر لامع تحاكي مظهرها الأملس المنحوت على طراز آرت ديكو. وفي المقدمة يقف غريملن أصلي مرسوم بالألوان نفسها، يحمل نجمة تناسب هذه الأداة.", zh: "金属灰色的立柱和一片光亮的红色织物，呼应了她光滑、雕塑般的装饰艺术风格。前方站着一个用同样颜色画成的原创小精灵，手里拿着一颗与本工具相配的星星。", sw: "Nguzo za kijivu cha metali na mtiririko wa kitambaa chekundu kinachong'aa vinakumbusha mwonekano wake laini na uliochongwa wa Art Deco. Mbele amesimama gremlin halisi aliyechorwa kwa rangi zilezile, akishika nyota inayolingana na zana hii.", sv: "Metallgrå pelare och ett svep av glansigt rött tyg påminner om hennes släta, skulpterade art déco-stil. Framför står en egen gremlin tecknad i samma färger, med en stjärna som passar det här verktyget." },
  "Watch how Logo Forge works — with voice": { es: "Mira cómo funciona Logo Forge, con voz", ar: "شاهد كيف يعمل Logo Forge — مع صوت", zh: "观看 Logo Forge 的使用方法（带语音）", sw: "Tazama jinsi Logo Forge inavyofanya kazi — kwa sauti", sv: "Se hur Logo Forge fungerar — med röst" },
  "Welcome to Logo Forge. Describe your business, and get a logo and a brand kit.": { es: "Bienvenido a Logo Forge. Describe tu negocio y obtén un logotipo y un kit de marca.", ar: "مرحبًا بك في Logo Forge. صِف نشاطك التجاري، واحصل على شعار ومجموعة هوية للعلامة التجارية.", zh: "欢迎使用 Logo Forge。描述你的生意，即可获得一个标志和一套品牌素材。", sw: "Karibu Logo Forge. Eleza biashara yako, na upate nembo na kifurushi cha chapa.", sv: "Välkommen till Logo Forge. Beskriv ditt företag och få en logotyp och ett varumärkespaket." },
  "Describe the business and the feeling you want, and add its name.": { es: "Describe el negocio y la sensación que buscas, y añade su nombre.", ar: "صِف النشاط التجاري والإحساس الذي تريده، وأضف اسمه.", zh: "描述你的生意和想要的感觉，并加上名称。", sw: "Eleza biashara na hisia unayotaka, na uongeze jina lake.", sv: "Beskriv företaget och känslan du vill ha, och lägg till namnet." },
  "Press Generate a logo and brand kit.": { es: "Pulsa Generar un logotipo y un kit de marca.", ar: "اضغط إنشاء شعار ومجموعة هوية.", zh: "按“生成标志和品牌素材”。", sw: "Bonyeza Tengeneza nembo na kifurushi cha chapa.", sv: "Tryck på Generera en logotyp och ett varumärkespaket." },
  "Here is your logo with colours, fonts and a small icon for your website tab.": { es: "Aquí tienes tu logotipo con colores, fuentes y un pequeño icono para la pestaña de tu web.", ar: "إليك شعارك مع الألوان والخطوط وأيقونة صغيرة لعلامة تبويب موقعك.", zh: "这就是你的标志，附带配色、字体和一个用于网站标签页的小图标。", sw: "Hii hapa nembo yako pamoja na rangi, fonti na aikoni ndogo ya kichupo cha tovuti yako.", sv: "Här är din logotyp med färger, typsnitt och en liten ikon för webbplatsens flik." },
  "Download the files you need: the logo, the favicon and the brand kit.": { es: "Descarga los archivos que necesites: el logotipo, el favicon y el kit de marca.", ar: "نزّل الملفات التي تحتاجها: الشعار وأيقونة الموقع ومجموعة الهوية.", zh: "下载你需要的文件：标志、网站图标和品牌素材包。", sw: "Pakua faili unazohitaji: nembo, favicon na kifurushi cha chapa.", sv: "Ladda ner filerna du behöver: logotypen, faviconen och varumärkespaketet." },
  "Now it is your turn. Open Logo Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Logo Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Logo Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Logo Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Logo Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Logo Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Logo Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Logo Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Logo Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Logo Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Logo Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Logo Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Tamara de Lempicka – click for more": { es: "Arte al estilo de Tamara de Lempicka: haz clic para saber más", ar: "رسم بأسلوب تامارا دي ليمبيكا – انقر لمعرفة المزيد", zh: "塔玛拉·德·蓝碧嘉风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Tamara de Lempicka – bofya kujua zaidi", sv: "Konst i Tamara de Lempickas stil – klicka för mer" },
  "e.g. A family-run plumbing company in Austin, TX. Friendly but no-nonsense tone.": { es: "p. ej. Una empresa familiar de fontanería en Austin, TX. Tono cercano pero directo.", ar: "مثلًا: شركة سباكة عائلية في أوستن، تكساس. نبرة ودية لكن جادة.", zh: "例如：得州奥斯汀的一家家族水管公司。语气友好但干脆。", sw: "k.m. Kampuni ya familia ya mabomba huko Austin, TX. Sauti ya kirafiki lakini ya moja kwa moja.", sv: "t.ex. Ett familjedrivet rörfirma i Austin, TX. Vänlig men rak ton." },
  "Leave blank to let the AI suggest one in the logo": { es: "Déjalo vacío para que la IA sugiera uno en el logotipo", ar: "اتركه فارغًا ليقترح الذكاء الاصطناعي واحدًا في الشعار", zh: "留空则由 AI 在标志中建议一个", sw: "Acha tupu ili AI ipendekeze moja kwenye nembo", sv: "Lämna tomt så föreslår AI:n en i logotypen" },
  "How to use Logo Forge": { es: "Cómo usar Logo Forge", ar: "كيفية استخدام Logo Forge", zh: "如何使用 Logo Forge", sw: "Jinsi ya kutumia Logo Forge", sv: "Så använder du Logo Forge" },
  "Logo Forge — free logo & favicon generator": { es: "Logo Forge — generador de logotipos y favicons gratis", ar: "Logo Forge — منشئ شعارات وأيقونات مواقع مجاني", zh: "Logo Forge — 免费标志和网站图标生成器", sw: "Logo Forge — kitengeneza nembo na favicon cha bure", sv: "Logo Forge — gratis generator för logotyper och favicons" }
});
