/* merge-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Cubism": { es: "Cubismo", ar: "التكعيبية", zh: "立体主义", sw: "Ukubism", sv: "Kubism" },
  "A French painter who invented Cubism with Picasso and brought in collage and musical instruments.": { es: "Un pintor francés que inventó el cubismo junto a Picasso e introdujo el collage y los instrumentos musicales.", ar: "رسام فرنسي ابتكر التكعيبية مع بيكاسو وأدخل الكولاج والآلات الموسيقية.", zh: "一位法国画家，与毕加索共同开创了立体主义，并引入了拼贴和乐器题材。", sw: "Mchoraji Mfaransa aliyebuni Ukubism pamoja na Picasso na kuleta kolaji na ala za muziki.", sv: "En fransk målare som skapade kubismen tillsammans med Picasso och förde in collage och musikinstrument." },
  "Muted brown planes, a guitar sound-hole and strings recall his Cubist still lifes. In front stands an original golem drawn in the same colours, holding a pair of scissors that fits this tool.": { es: "Planos marrones apagados, la boca de una guitarra y sus cuerdas recuerdan sus bodegones cubistas. Delante hay un gólem original dibujado con los mismos colores, que sostiene unas tijeras acordes con esta herramienta.", ar: "مسطحات بنية خافتة، وفتحة صوت غيتار وأوتاره، تذكّر بطبيعته الصامتة التكعيبية. وفي المقدمة يقف غولم أصلي مرسوم بالألوان نفسها، يحمل مقصًا يناسب هذه الأداة.", zh: "柔和的棕色块面、吉他音孔和琴弦，让人想起他的立体主义静物画。前方站着一个用同样颜色画成的原创石魔像，手里拿着一把与本工具相配的剪刀。", sw: "Bapa za kahawia hafifu, tundu la sauti la gitaa na nyuzi zake zinakumbusha michoro yake ya vitu tulivu ya Kikubism. Mbele amesimama golemu halisi aliyechorwa kwa rangi zilezile, akishika mkasi unaolingana na zana hii.", sv: "Dämpade bruna ytor, ett gitarrljudhål och strängar påminner om hans kubistiska stilleben. Framför står en egen golem tecknad i samma färger, med en sax som passar det här verktyget." },
  "Watch how Merge Forge works — with voice": { es: "Mira cómo funciona Merge Forge, con voz", ar: "شاهد كيف يعمل Merge Forge — مع صوت", zh: "观看 Merge Forge 的使用方法（带语音）", sw: "Tazama jinsi Merge Forge inavyofanya kazi — kwa sauti", sv: "Se hur Merge Forge fungerar — med röst" },
  "Welcome to Merge Forge. Combine pictures and clips with text and music into one video.": { es: "Bienvenido a Merge Forge. Combina imágenes y clips con texto y música en un solo vídeo.", ar: "مرحبًا بك في Merge Forge. ادمج الصور والمقاطع مع النص والموسيقى في فيديو واحد.", zh: "欢迎使用 Merge Forge。把图片和片段连同文字、音乐合成一个视频。", sw: "Karibu Merge Forge. Unganisha picha na klipu pamoja na maandishi na muziki kuwa video moja.", sv: "Välkommen till Merge Forge. Kombinera bilder och klipp med text och musik till en video." },
  "Add your images and clips in order.": { es: "Añade tus imágenes y clips en orden.", ar: "أضف صورك ومقاطعك بالترتيب.", zh: "按顺序添加你的图片和片段。", sw: "Ongeza picha na klipu zako kwa mpangilio.", sv: "Lägg till dina bilder och klipp i ordning." },
  "Choose a transition, the shape, and add a caption.": { es: "Elige una transición y el formato, y añade un subtítulo.", ar: "اختر انتقالًا والشكل، وأضف تعليقًا.", zh: "选择转场和画面形状，并添加字幕。", sw: "Chagua mpito, umbo, na uongeze maelezo.", sv: "Välj en övergång och ett format, och lägg till en bildtext." },
  "Pick background music, or record your own voice.": { es: "Elige música de fondo o graba tu propia voz.", ar: "اختر موسيقى خلفية، أو سجّل صوتك.", zh: "选择背景音乐，或录下你自己的声音。", sw: "Chagua muziki wa mandharinyuma, au rekodi sauti yako mwenyewe.", sv: "Välj bakgrundsmusik eller spela in din egen röst." },
  "Press Merge and render video.": { es: "Pulsa Unir y renderizar vídeo.", ar: "اضغط دمج وتصيير الفيديو.", zh: "按“合并并渲染视频”。", sw: "Bonyeza Unganisha na utengeneze video.", sv: "Tryck på Slå ihop och rendera video." },
  "Play the preview, then download the finished video.": { es: "Reproduce la vista previa y luego descarga el vídeo terminado.", ar: "شغّل المعاينة، ثم نزّل الفيديو النهائي.", zh: "播放预览，然后下载完成的视频。", sw: "Cheza uhakiki, kisha upakue video iliyokamilika.", sv: "Spela upp förhandsvisningen och ladda sedan ner den färdiga videon." },
  "Now it is your turn. Open Merge Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Merge Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Merge Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Merge Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Merge Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Merge Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Merge Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Merge Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Merge Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Merge Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Merge Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Merge Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Georges Braque – click for more": { es: "Arte al estilo de Georges Braque: haz clic para saber más", ar: "رسم بأسلوب جورج براك – انقر لمعرفة المزيد", zh: "乔治·布拉克风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Georges Braque – bofya kujua zaidi", sv: "Konst i Georges Braques stil – klicka för mer" },
  "Transition between images": { es: "Transición entre imágenes", ar: "الانتقال بين الصور", zh: "图片之间的转场", sw: "Mpito kati ya picha", sv: "Övergång mellan bilder" },
  "e.g. Believe in yourself": { es: "p. ej., Cree en ti", ar: "مثلًا: آمن بنفسك", zh: "例如：相信你自己", sw: "k.m. Jiamini", sv: "t.ex. Tro på dig själv" },
  "How to use Merge Forge": { es: "Cómo usar Merge Forge", ar: "كيفية استخدام Merge Forge", zh: "如何使用 Merge Forge", sw: "Jinsi ya kutumia Merge Forge", sv: "Så använder du Merge Forge" },
  "Merge Forge — combine images, clips and music into one video": { es: "Merge Forge — combina imágenes, clips y música en un solo vídeo", ar: "Merge Forge — ادمج الصور والمقاطع والموسيقى في فيديو واحد", zh: "Merge Forge — 把图片、片段和音乐合成一个视频", sw: "Merge Forge — unganisha picha, klipu na muziki kuwa video moja", sv: "Merge Forge — kombinera bilder, klipp och musik till en video" }
});
