/* name-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "A Belgian Surrealist who made ordinary things puzzling: bowler hats, clouds, apples and pipes.": { es: "Un surrealista belga que volvió enigmáticas las cosas corrientes: bombines, nubes, manzanas y pipas.", ar: "سريالي بلجيكي جعل الأشياء العادية محيّرة: القبعات المستديرة والغيوم والتفاح والغلايين.", zh: "一位比利时超现实主义画家，把寻常之物变得令人费解：圆顶礼帽、云朵、苹果和烟斗。", sw: "Msurealisti wa Kibelgiji aliyefanya vitu vya kawaida kuwa fumbo: kofia za bakuli, mawingu, matufaha na viko.", sv: "En belgisk surrealist som gjorde vardagliga saker gåtfulla: kubbar, moln, äpplen och pipor." },
  "White clouds in a blue sky with a floating bowler hat and a green apple are his motifs. In front stands an original troll drawn in the same colours, holding a speech bubble that fits this tool.": { es: "Nubes blancas en un cielo azul con un bombín flotante y una manzana verde son sus motivos. Delante hay un trol original dibujado con los mismos colores, que sostiene un bocadillo de diálogo acorde con esta herramienta.", ar: "غيوم بيضاء في سماء زرقاء مع قبعة مستديرة طافية وتفاحة خضراء هي زخارفه المعهودة. وفي المقدمة يقف قزم ترول أصلي مرسوم بالألوان نفسها، يحمل فقاعة كلام تناسب هذه الأداة.", zh: "蓝天白云中漂浮的圆顶礼帽和一只青苹果，是他标志性的意象。前方站着一个用同样颜色画成的原创巨魔，手里拿着一个与本工具相配的对话气泡。", sw: "Mawingu meupe katika anga la bluu pamoja na kofia ya bakuli inayoelea na tufaha la kijani ndiyo motifu zake. Mbele amesimama zimwi halisi aliyechorwa kwa rangi zilezile, akishika kiputo cha maneno kinacholingana na zana hii.", sv: "Vita moln på en blå himmel med en svävande kubb och ett grönt äpple är hans motiv. Framför står ett eget troll tecknat i samma färger, med en pratbubbla som passar det här verktyget." },
  "Watch how Name Forge works — with voice": { es: "Mira cómo funciona Name Forge, con voz", ar: "شاهد كيف يعمل Name Forge — مع صوت", zh: "观看 Name Forge 的使用方法（带语音）", sw: "Tazama jinsi Name Forge inavyofanya kazi — kwa sauti", sv: "Se hur Name Forge fungerar — med röst" },
  "Welcome to Name Forge. It helps you brainstorm a name for your business.": { es: "Bienvenido a Name Forge. Te ayuda a buscar ideas de nombre para tu negocio.", ar: "مرحبًا بك في Name Forge. يساعدك على توليد أفكار لاسم نشاطك التجاري.", zh: "欢迎使用 Name Forge。它帮你为自己的生意头脑风暴出一个名字。", sw: "Karibu Name Forge. Inakusaidia kubuni jina la biashara yako.", sv: "Välkommen till Name Forge. Den hjälper dig att brainstorma ett namn för ditt företag." },
  "Describe what your business does, and choose a style.": { es: "Describe a qué se dedica tu negocio y elige un estilo.", ar: "صف ما يقوم به نشاطك التجاري، واختر أسلوبًا.", zh: "描述你的生意是做什么的，并选择一种风格。", sw: "Eleza biashara yako inafanya nini, na uchague mtindo.", sv: "Beskriv vad ditt företag gör och välj en stil." },
  "Press Generate names.": { es: "Pulsa Generar nombres.", ar: "اضغط إنشاء أسماء.", zh: "按“生成名称”。", sw: "Bonyeza Tengeneza majina.", sv: "Tryck på Generera namn." },
  "Shortlist the names you like and check whether the web address is free. Press More ideas for a new batch.": { es: "Guarda en tu lista los nombres que te gusten y comprueba si la dirección web está libre. Pulsa Más ideas para una nueva tanda.", ar: "ضع الأسماء التي تعجبك في قائمة مختصرة وتحقق مما إذا كان عنوان الموقع متاحًا. اضغط المزيد من الأفكار للحصول على دفعة جديدة.", zh: "把喜欢的名字加入候选名单，并检查网址是否可用。按“更多创意”获取新一批。", sw: "Weka kwenye orodha fupi majina unayoyapenda na uangalie kama anwani ya wavuti iko wazi. Bonyeza Mawazo zaidi kupata kundi jipya.", sv: "Spara namnen du gillar på en kortlista och kolla om webbadressen är ledig. Tryck på Fler idéer för en ny omgång." },
  "Now it is your turn. Open Name Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Name Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Name Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Name Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Name Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Name Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Name Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Name Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Name Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Name Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Name Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Name Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of René Magritte – click for more": { es: "Arte al estilo de René Magritte: haz clic para saber más", ar: "رسم بأسلوب رينيه ماغريت – انقر لمعرفة المزيد", zh: "勒内·马格利特风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa René Magritte – bofya kujua zaidi", sv: "Konst i René Magrittes stil – klicka för mer" },
  "coffee, dog walking, web design…": { es: "café, paseo de perros, diseño web…", ar: "قهوة، تمشية الكلاب، تصميم المواقع…", zh: "咖啡、遛狗、网页设计…", sw: "kahawa, kutembeza mbwa, usanifu wa wavuti…", sv: "kaffe, hundpromenader, webbdesign…" },
  "How to use Name Forge": { es: "Cómo usar Name Forge", ar: "كيفية استخدام Name Forge", zh: "如何使用 Name Forge", sw: "Jinsi ya kutumia Name Forge", sv: "Så använder du Name Forge" },
  "Name Forge — free business name generator": { es: "Name Forge — generador de nombres de negocio gratis", ar: "Name Forge — منشئ أسماء تجارية مجاني", zh: "Name Forge — 免费商业名称生成器", sw: "Name Forge — kitengeneza majina ya biashara cha bure", sv: "Name Forge — gratis generator för företagsnamn" }
});
