/* post-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Pop Art": { es: "Arte pop", ar: "فن البوب", zh: "波普艺术", sw: "Sanaa ya Pop", sv: "Popkonst" },
  "An American Pop artist of repeated, brightly coloured silk-screen images like the Marilyn Diptych and Campbell's Soup Cans.": { es: "Un artista pop estadounidense de imágenes serigrafiadas repetidas y de colores vivos, como el Díptico de Marilyn y las Latas de sopa Campbell.", ar: "فنان بوب أمريكي اشتهر بالصور المطبوعة بالشاشة الحريرية المكررة والزاهية الألوان، مثل \"ثنائية مارلين\" و\"علب حساء كامبل\".", zh: "一位美国波普艺术家，以重复的鲜艳丝网印刷图像闻名，如《玛丽莲双联画》和《金宝汤罐头》。", sw: "Msanii wa Pop wa Kimarekani wa picha za uchapishaji wa skrini ya hariri zinazojirudia zenye rangi angavu, kama Marilyn Diptych na Campbell's Soup Cans.", sv: "En amerikansk popkonstnär känd för upprepade, starkt färgade screentryck som Marilyn Diptych och Campbell's Soup Cans." },
  "A grid of the same piece of fruit repeated in clashing neon colours is his silk-screen style. In front stands an original gremlin drawn in the same colours, holding a camera that fits this tool.": { es: "Una cuadrícula con la misma fruta repetida en colores neón que chocan entre sí es su estilo serigráfico. Delante hay un gremlin original dibujado con los mismos colores, que sostiene una cámara acorde con esta herramienta.", ar: "شبكة من قطعة الفاكهة نفسها مكررة بألوان نيون متنافرة هي أسلوبه في الطباعة الحريرية. وفي المقدمة يقف غريملن أصلي مرسوم بالألوان نفسها، يحمل كاميرا تناسب هذه الأداة.", zh: "同一颗水果以撞色霓虹色重复排成网格，这就是他的丝网印刷风格。前方站着一个用同样颜色画成的原创小精灵，手里拿着一台与本工具相配的相机。", sw: "Gridi ya tunda lilelile likijirudia kwa rangi za neon zinazogongana ndio mtindo wake wa skrini ya hariri. Mbele amesimama gremlin halisi aliyechorwa kwa rangi zilezile, akishika kamera inayolingana na zana hii.", sv: "Ett rutnät av samma frukt upprepad i krockande neonfärger är hans screentrycksstil. Framför står en egen gremlin tecknad i samma färger, med en kamera som passar det här verktyget." },
  "💬 Discord (not connected)": { es: "💬 Discord (no conectado)", ar: "💬 Discord (غير متصل)", zh: "💬 Discord（未连接）", sw: "💬 Discord (haijaunganishwa)", sv: "💬 Discord (inte ansluten)" },
  "🦋 Bluesky (not connected)": { es: "🦋 Bluesky (no conectado)", ar: "🦋 Bluesky (غير متصل)", zh: "🦋 Bluesky（未连接）", sw: "🦋 Bluesky (haijaunganishwa)", sv: "🦋 Bluesky (inte ansluten)" },
  "🐘 Mastodon (not connected)": { es: "🐘 Mastodon (no conectado)", ar: "🐘 Mastodon (غير متصل)", zh: "🐘 Mastodon（未连接）", sw: "🐘 Mastodon (haijaunganishwa)", sv: "🐘 Mastodon (inte ansluten)" },
  "Watch how Post Forge works — with voice": { es: "Mira cómo funciona Post Forge, con voz", ar: "شاهد كيف يعمل Post Forge — مع صوت", zh: "观看 Post Forge 的使用方法（带语音）", sw: "Tazama jinsi Post Forge inavyofanya kazi — kwa sauti", sv: "Se hur Post Forge fungerar — med röst" },
  "Welcome to Post Forge. Write one announcement and post it to several networks at once.": { es: "Bienvenido a Post Forge. Escribe un anuncio y publícalo en varias redes a la vez.", ar: "مرحبًا بك في Post Forge. اكتب إعلانًا واحدًا وانشره على عدة شبكات دفعة واحدة.", zh: "欢迎使用 Post Forge。写一条公告，同时发布到多个平台。", sw: "Karibu Post Forge. Andika tangazo moja na ulichapishe kwenye mitandao kadhaa kwa wakati mmoja.", sv: "Välkommen till Post Forge. Skriv ett meddelande och publicera det i flera nätverk på en gång." },
  "Connect your accounts once. The keys are saved only in this browser.": { es: "Conecta tus cuentas una sola vez. Las claves se guardan solo en este navegador.", ar: "اربط حساباتك مرة واحدة. تُحفظ المفاتيح في هذا المتصفح فقط.", zh: "只需连接一次账号。密钥仅保存在此浏览器中。", sw: "Unganisha akaunti zako mara moja. Funguo huhifadhiwa kwenye kivinjari hiki pekee.", sv: "Anslut dina konton en gång. Nycklarna sparas bara i den här webbläsaren." },
  "Write your announcement, add a link and an image.": { es: "Escribe tu anuncio y añade un enlace y una imagen.", ar: "اكتب إعلانك، وأضف رابطًا وصورة.", zh: "写下你的公告，添加一个链接和一张图片。", sw: "Andika tangazo lako, ongeza kiungo na picha.", sv: "Skriv ditt meddelande och lägg till en länk och en bild." },
  "Tick where it should go, and press Post now.": { es: "Marca dónde debe publicarse y pulsa Publicar ahora.", ar: "حدّد أين يجب أن يُنشر، واضغط انشر الآن.", zh: "勾选要发布到哪里，然后按“立即发布”。", sw: "Weka alama mahali linapopaswa kwenda, na ubonyeze Chapisha sasa.", sv: "Bocka för var det ska publiceras och tryck på Publicera nu." },
  "Now it is your turn. Open Post Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Post Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Post Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Post Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Post Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Post Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Post Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Post Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Post Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Post Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Post Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Post Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Andy Warhol – click for more": { es: "Arte al estilo de Andy Warhol: haz clic para saber más", ar: "رسم بأسلوب آندي وارهول – انقر لمعرفة المزيد", zh: "安迪·沃霍尔风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Andy Warhol – bofya kujua zaidi", sv: "Konst i Andy Warhols stil – klicka för mer" },
  "paste your token": { es: "pega tu token", ar: "الصق الرمز المميز", zh: "粘贴你的令牌", sw: "bandika tokeni yako", sv: "klistra in din token" },
  "New tool just launched: Paint Forge — a free layered image editor, right in your browser.": { es: "Nueva herramienta: Paint Forge, un editor de imágenes por capas gratuito, en tu navegador.", ar: "أداة جديدة أُطلقت للتو: Paint Forge — محرر صور مجاني بطبقات، مباشرة في متصفحك.", zh: "新工具上线：Paint Forge——免费的分层图片编辑器，直接在浏览器中使用。", sw: "Zana mpya imezinduliwa: Paint Forge — kihariri cha picha cha bure chenye matabaka, moja kwa moja kwenye kivinjari chako.", sv: "Nytt verktyg lanserat: Paint Forge — en gratis bildredigerare med lager, direkt i webbläsaren." },
  "How to use Post Forge": { es: "Cómo usar Post Forge", ar: "كيفية استخدام Post Forge", zh: "如何使用 Post Forge", sw: "Jinsi ya kutumia Post Forge", sv: "Så använder du Post Forge" },
  "Post Forge — post an announcement to Discord, Bluesky & Mastodon at once": { es: "Post Forge — publica un anuncio en Discord, Bluesky y Mastodon a la vez", ar: "Post Forge — انشر إعلانًا على Discord وBluesky وMastodon دفعة واحدة", zh: "Post Forge — 一次把公告发布到 Discord、Bluesky 和 Mastodon", sw: "Post Forge — chapisha tangazo kwenye Discord, Bluesky na Mastodon kwa wakati mmoja", sv: "Post Forge — publicera ett meddelande på Discord, Bluesky och Mastodon samtidigt" }
});
