/* qr-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "De Stijl (Neoplasticism)": { es: "De Stijl (neoplasticismo)", ar: "دي ستايل (اللدائنية الجديدة)", zh: "风格派（新造型主义）", sw: "De Stijl (Neoplastiki)", sv: "De Stijl (neoplasticism)" },
  "A Dutch painter who reduced art to black lines and blocks of primary colour.": { es: "Un pintor neerlandés que redujo el arte a líneas negras y bloques de colores primarios.", ar: "رسام هولندي اختزل الفن في خطوط سوداء وكتل من الألوان الأساسية.", zh: "一位荷兰画家，把艺术简化为黑色线条和原色色块。", sw: "Mchoraji wa Kiholanzi aliyepunguza sanaa kuwa mistari myeusi na vitalu vya rangi za msingi.", sv: "En nederländsk målare som reducerade konsten till svarta linjer och block i primärfärger." },
  "Thick black lines dividing white, red, blue and yellow rectangles are his Compositions. In front stands an original robot drawn in the same colours, holding a star that fits this tool.": { es: "Gruesas líneas negras que dividen rectángulos blancos, rojos, azules y amarillos son sus Composiciones. Delante hay un robot original dibujado con los mismos colores, que sostiene una estrella acorde con esta herramienta.", ar: "خطوط سوداء سميكة تقسم مستطيلات بيضاء وحمراء وزرقاء وصفراء هي \"تكويناته\". وفي المقدمة يقف روبوت أصلي مرسوم بالألوان نفسها، يحمل نجمة تناسب هذه الأداة.", zh: "粗黑线条分隔出白、红、蓝、黄色矩形，这就是他的《构图》系列。前方站着一个用同样颜色画成的原创机器人，手里拿着一颗与本工具相配的星星。", sw: "Mistari minene myeusi inayogawa mistatili myeupe, myekundu, ya bluu na ya njano ndiyo Compositions zake. Mbele amesimama roboti halisi aliyechorwa kwa rangi zilezile, akishika nyota inayolingana na zana hii.", sv: "Tjocka svarta linjer som delar upp vita, röda, blå och gula rektanglar är hans Kompositioner. Framför står en egen robot tecknad i samma färger, med en stjärna som passar det här verktyget." },
  "Could not generate a QR code for that input — try shorter text.": { es: "No se pudo generar un código QR con eso; prueba con un texto más corto.", ar: "تعذّر إنشاء رمز QR لهذا الإدخال — جرّب نصًا أقصر.", zh: "无法为该输入生成二维码——请尝试更短的文字。", sw: "Imeshindikana kutengeneza msimbo wa QR kwa ingizo hilo — jaribu maandishi mafupi zaidi.", sv: "Kunde inte skapa en QR-kod för den inmatningen — prova en kortare text." },
  "Watch how QR Forge works — with voice": { es: "Mira cómo funciona QR Forge, con voz", ar: "شاهد كيف يعمل QR Forge — مع صوت", zh: "观看 QR Forge 的使用方法（带语音）", sw: "Tazama jinsi QR Forge inavyofanya kazi — kwa sauti", sv: "Se hur QR Forge fungerar — med röst" },
  "Welcome to QR Forge. Let us make a QR code that people can scan with their phone camera.": { es: "Bienvenido a QR Forge. Vamos a crear un código QR que la gente pueda escanear con la cámara del teléfono.", ar: "مرحبًا بك في QR Forge. لنصنع رمز QR يمكن للناس مسحه بكاميرا هواتفهم.", zh: "欢迎使用 QR Forge。我们来做一个大家可以用手机相机扫描的二维码。", sw: "Karibu QR Forge. Hebu tutengeneze msimbo wa QR ambao watu wanaweza kuchanganua kwa kamera ya simu zao.", sv: "Välkommen till QR Forge. Vi gör en QR-kod som folk kan skanna med mobilkameran." },
  "First choose what the code is for: a link or text, a Wi-Fi network, a contact card, a phone number or an email.": { es: "Primero elige para qué es el código: un enlace o texto, una red Wi-Fi, una tarjeta de contacto, un número de teléfono o un correo electrónico.", ar: "اختر أولًا الغرض من الرمز: رابط أو نص، أو شبكة Wi-Fi، أو بطاقة جهة اتصال، أو رقم هاتف، أو بريد إلكتروني.", zh: "先选择二维码的用途：链接或文字、Wi-Fi 网络、联系人名片、电话号码或电子邮件。", sw: "Kwanza chagua msimbo ni wa nini: kiungo au maandishi, mtandao wa Wi-Fi, kadi ya mawasiliano, nambari ya simu au barua pepe.", sv: "Välj först vad koden är till för: en länk eller text, ett wifi-nätverk, ett kontaktkort, ett telefonnummer eller ett mejl." },
  "Type the link you want people to open. The code updates instantly as you type.": { es: "Escribe el enlace que quieres que abra la gente. El código se actualiza al instante mientras escribes.", ar: "اكتب الرابط الذي تريد أن يفتحه الناس. يتحدّث الرمز فورًا أثناء الكتابة.", zh: "输入你希望别人打开的链接。二维码会随着输入即时更新。", sw: "Andika kiungo unachotaka watu wafungue. Msimbo husasishwa papo hapo unapoandika.", sv: "Skriv länken du vill att folk ska öppna. Koden uppdateras direkt medan du skriver." },
  "Pick the size and colours. A dark code on a light background scans best.": { es: "Elige el tamaño y los colores. Un código oscuro sobre fondo claro se escanea mejor.", ar: "اختر الحجم والألوان. الرمز الداكن على خلفية فاتحة يُمسح بأفضل شكل.", zh: "选择尺寸和颜色。浅色背景上的深色二维码最容易扫描。", sw: "Chagua ukubwa na rangi. Msimbo mweusi juu ya mandharinyuma angavu huchanganuliwa vizuri zaidi.", sv: "Välj storlek och färger. En mörk kod på ljus bakgrund skannas bäst." },
  "Scan it with your phone to test it, then download the finished code as a picture.": { es: "Escanéalo con tu teléfono para probarlo y luego descarga el código terminado como imagen.", ar: "امسحه بهاتفك لتختبره، ثم نزّل الرمز النهائي كصورة.", zh: "用手机扫一扫测试一下，然后把做好的二维码下载为图片。", sw: "Uchanganue kwa simu yako kuujaribu, kisha upakue msimbo uliokamilika kama picha.", sv: "Skanna den med mobilen för att testa och ladda sedan ner den färdiga koden som en bild." },
  "Now it is your turn. Open QR Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre QR Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح QR Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 QR Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua QR Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna QR Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to QR Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a QR Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في QR Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 QR Forge。本演示使用本页上真实的工具控件。", sw: "Karibu QR Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till QR Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Piet Mondrian – click for more": { es: "Arte al estilo de Piet Mondrian: haz clic para saber más", ar: "رسم بأسلوب بيت موندريان – انقر لمعرفة المزيد", zh: "皮特·蒙德里安风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Piet Mondrian – bofya kujua zaidi", sv: "Konst i Piet Mondrians stil – klicka för mer" },
  "Leave blank if open": { es: "Déjalo vacío si es abierta", ar: "اتركه فارغًا إذا كانت الشبكة مفتوحة", zh: "如果是开放网络请留空", sw: "Acha tupu kama mtandao uko wazi", sv: "Lämna tomt om nätet är öppet" },
  "How to use QR Forge": { es: "Cómo usar QR Forge", ar: "كيفية استخدام QR Forge", zh: "如何使用 QR Forge", sw: "Jinsi ya kutumia QR Forge", sv: "Så använder du QR Forge" },
  "QR Forge — free QR code generator": { es: "QR Forge — generador de códigos QR gratis", ar: "QR Forge — منشئ رموز QR مجاني", zh: "QR Forge — 免费二维码生成器", sw: "QR Forge — kitengeneza msimbo wa QR cha bure", sv: "QR Forge — gratis QR-kodgenerator" }
});
