/* record-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Venetian Renaissance": { es: "Renacimiento veneciano", ar: "عصر النهضة البندقي", zh: "威尼斯文艺复兴", sw: "Mwamko wa Venisi", sv: "Venetiansk renässans" },
  "The leading painter of Renaissance Venice, famous for rich, glowing colour and loose, expressive brushwork.": { es: "El pintor más destacado de la Venecia renacentista, famoso por su color rico y luminoso y su pincelada suelta y expresiva.", ar: "أبرز رسامي البندقية في عصر النهضة، اشتهر بألوانه الغنية المتوهجة وضربات فرشاته الحرة المعبّرة.", zh: "文艺复兴时期威尼斯最重要的画家，以丰富、明亮的色彩和松弛而富有表现力的笔触著称。", sw: "Mchoraji mkuu wa Venisi wakati wa Mwamko, maarufu kwa rangi tajiri zinazong'aa na mipigo ya brashi huru yenye hisia.", sv: "Renässansens ledande målare i Venedig, berömd för rik, glödande färg och fritt, uttrycksfullt penselarbete." },
  "The blue-to-gold sky and the sweep of deep red drapery echo his colour and his flowing cloth. In front stands an original cyclops drawn in the same colours, holding a camera that fits this tool.": { es: "El cielo que pasa del azul al dorado y el vuelo de los paños rojo intenso evocan su color y sus telas fluidas. Delante hay un cíclope original dibujado con los mismos colores, que sostiene una cámara acorde con esta herramienta.", ar: "السماء المتدرجة من الأزرق إلى الذهبي وانسياب الأقمشة الحمراء الداكنة تحاكي ألوانه وأقمشته المنسدلة. وفي المقدمة يقف سايكلوب أصلي مرسوم بالألوان نفسها، يحمل كاميرا تناسب هذه الأداة.", zh: "由蓝渐变到金的天空和一大片深红色衣褶，呼应了他的色彩和飘逸的布料。前方站着一个用同样颜色画成的原创独眼巨人，手里拿着一台与本工具相配的摄像机。", sw: "Anga la bluu hadi dhahabu na mtiririko wa kitambaa chekundu kilichokolea vinakumbusha rangi zake na vitambaa vyake vinavyotiririka. Mbele amesimama saiklopsi halisi aliyechorwa kwa rangi zilezile, akishika kamera inayolingana na zana hii.", sv: "Himlen från blått till guld och svepet av djupröda draperier påminner om hans färger och flytande tyger. Framför står en egen cyklop tecknad i samma färger, med en kamera som passar det här verktyget." },
  "Watch how Record Forge works — with voice": { es: "Mira cómo funciona Record Forge, con voz", ar: "شاهد كيف يعمل Record Forge — مع صوت", zh: "观看 Record Forge 的使用方法（带语音）", sw: "Tazama jinsi Record Forge inavyofanya kazi — kwa sauti", sv: "Se hur Record Forge fungerar — med röst" },
  "Welcome to Record Forge. Record your screen with your voice, to show someone how something works.": { es: "Bienvenido a Record Forge. Graba tu pantalla con tu voz para enseñar a alguien cómo funciona algo.", ar: "مرحبًا بك في Record Forge. سجّل شاشتك مع صوتك، لتُري أحدهم كيف يعمل شيء ما.", zh: "欢迎使用 Record Forge。录制屏幕并配上你的讲解，向别人演示某样东西怎么用。", sw: "Karibu Record Forge. Rekodi skrini yako pamoja na sauti yako, kumwonyesha mtu jinsi kitu kinavyofanya kazi.", sv: "Välkommen till Record Forge. Spela in skärmen med din röst för att visa någon hur något fungerar." },
  "Choose what to include: your microphone, the computer sound, and your webcam in a corner.": { es: "Elige qué incluir: tu micrófono, el sonido del ordenador y tu cámara web en una esquina.", ar: "اختر ما تريد تضمينه: الميكروفون، وصوت الحاسوب، وكاميرا الويب في الزاوية.", zh: "选择要包含的内容：你的麦克风、电脑声音，以及角落里的摄像头画面。", sw: "Chagua cha kujumuisha: maikrofoni yako, sauti ya kompyuta, na kamera yako ya wavuti kwenye kona.", sv: "Välj vad som ska med: din mikrofon, datorns ljud och din webbkamera i ett hörn." },
  "Press Start recording, and choose the screen, window or browser tab to record.": { es: "Pulsa Empezar a grabar y elige la pantalla, ventana o pestaña del navegador que quieres grabar.", ar: "اضغط بدء التسجيل، واختر الشاشة أو النافذة أو علامة تبويب المتصفح المراد تسجيلها.", zh: "按“开始录制”，然后选择要录制的屏幕、窗口或浏览器标签页。", sw: "Bonyeza Anza kurekodi, na uchague skrini, dirisha au kichupo cha kivinjari cha kurekodi.", sv: "Tryck på Starta inspelning och välj skärmen, fönstret eller webbläsarfliken som ska spelas in." },
  "Show the task and explain as you go. When you stop, trim the start and end and download the recording.": { es: "Muestra la tarea y explícala sobre la marcha. Cuando pares, recorta el principio y el final y descarga la grabación.", ar: "اعرض المهمة واشرحها أثناء ذلك. عندما تتوقف، قصّ البداية والنهاية ونزّل التسجيل.", zh: "边演示任务边讲解。停止后，修剪开头和结尾，然后下载录像。", sw: "Onyesha kazi na ueleze unapoendelea. Ukisimamisha, kata mwanzo na mwisho kisha upakue rekodi.", sv: "Visa uppgiften och förklara under tiden. När du stoppar trimmar du början och slutet och laddar ner inspelningen." },
  "Now it is your turn. Open Record Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Record Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Record Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Record Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Record Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Record Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Record Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Record Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Record Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Record Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Record Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Record Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Titian – click for more": { es: "Arte al estilo de Tiziano: haz clic para saber más", ar: "رسم بأسلوب تيتيان – انقر لمعرفة المزيد", zh: "提香风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Titian – bofya kujua zaidi", sv: "Konst i Tizians stil – klicka för mer" },
  "How to set up my project": { es: "Cómo configurar mi proyecto", ar: "كيفية إعداد مشروعي", zh: "如何设置我的项目", sw: "Jinsi ya kuweka mradi wangu", sv: "Så konfigurerar jag mitt projekt" },
  "Screen recording made with Record Forge.": { es: "Grabación de pantalla hecha con Record Forge.", ar: "تسجيل شاشة صُنع باستخدام Record Forge.", zh: "用 Record Forge 制作的屏幕录像。", sw: "Rekodi ya skrini iliyotengenezwa kwa Record Forge.", sv: "Skärminspelning gjord med Record Forge." },
  "tutorial, screen recording, how-to": { es: "tutorial, grabación de pantalla, cómo se hace", ar: "شرح، تسجيل الشاشة، طريقة الاستخدام", zh: "教程, 屏幕录制, 使用方法", sw: "mafunzo, kurekodi skrini, jinsi ya", sv: "handledning, skärminspelning, instruktioner" },
  "How to use Record Forge": { es: "Cómo usar Record Forge", ar: "كيفية استخدام Record Forge", zh: "如何使用 Record Forge", sw: "Jinsi ya kutumia Record Forge", sv: "Så använder du Record Forge" },
  "Record Forge — screen recording with voice narration": { es: "Record Forge — grabación de pantalla con narración de voz", ar: "Record Forge — تسجيل الشاشة مع تعليق صوتي", zh: "Record Forge — 带语音讲解的屏幕录制", sw: "Record Forge — kurekodi skrini pamoja na masimulizi ya sauti", sv: "Record Forge — skärminspelning med berättarröst" }
});
