/* screen-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Pop Art (British)": { es: "Arte pop (británico)", ar: "فن البوب (البريطاني)", zh: "波普艺术（英国）", sw: "Sanaa ya Pop (ya Uingereza)", sv: "Popkonst (brittisk)" },
  "A British painter famous for sunny Californian swimming pools such as A Bigger Splash.": { es: "Un pintor británico famoso por sus soleadas piscinas californianas, como A Bigger Splash.", ar: "رسام بريطاني اشتهر بأحواض السباحة المشمسة في كاليفورنيا، مثل لوحة \"A Bigger Splash\".", zh: "一位英国画家，以阳光灿烂的加州泳池画作闻名，如《更大的水花》。", sw: "Mchoraji Mwingereza maarufu kwa mabwawa ya kuogelea yenye jua ya California kama A Bigger Splash.", sv: "En brittisk målare känd för soliga kaliforniska simbassänger som A Bigger Splash." },
  "A bright blue pool with wavy light lines and a white splash is from A Bigger Splash. In front stands an original axolotl drawn in the same colours, holding a laptop that fits this tool.": { es: "Una piscina azul intenso con líneas de luz onduladas y un chapoteo blanco viene de A Bigger Splash. Delante hay un ajolote original dibujado con los mismos colores, que sostiene un portátil acorde con esta herramienta.", ar: "حوض سباحة أزرق زاهٍ بخطوط ضوء متموجة ورذاذ أبيض مستوحى من \"A Bigger Splash\". وفي المقدمة يقف أكسولوتل أصلي مرسوم بالألوان نفسها، يحمل حاسوبًا محمولًا يناسب هذه الأداة.", zh: "带波浪光纹和白色水花的亮蓝色泳池出自《更大的水花》。前方站着一只用同样颜色画成的原创六角恐龙，手里拿着一台与本工具相配的笔记本电脑。", sw: "Bwawa la bluu angavu lenye mistari ya mwanga inayopinda na mrusho mweupe wa maji linatoka A Bigger Splash. Mbele amesimama axolotl halisi aliyechorwa kwa rangi zilezile, akishika kompyuta mpakato inayolingana na zana hii.", sv: "En klarblå pool med vågiga ljuslinjer och ett vitt plask kommer från A Bigger Splash. Framför står en egen axolotl tecknad i samma färger, med en bärbar dator som passar det här verktyget." },
  "Watch how Screen Share Forge works — with voice": { es: "Mira cómo funciona Screen Share Forge, con voz", ar: "شاهد كيف يعمل Screen Share Forge — مع صوت", zh: "观看 Screen Share Forge 的使用方法（带语音）", sw: "Tazama jinsi Screen Share Forge inavyofanya kazi — kwa sauti", sv: "Se hur Screen Share Forge fungerar — med röst" },
  "Welcome to Screen Share Forge. Help someone by seeing their screen live, without installing anything.": { es: "Bienvenido a Screen Share Forge. Ayuda a alguien viendo su pantalla en directo, sin instalar nada.", ar: "مرحبًا بك في Screen Share Forge. ساعد شخصًا برؤية شاشته مباشرة، دون تثبيت أي شيء.", zh: "欢迎使用 Screen Share Forge。实时查看对方的屏幕来帮助他们，无需安装任何东西。", sw: "Karibu Screen Share Forge. Msaidie mtu kwa kuona skrini yake moja kwa moja, bila kusakinisha chochote.", sv: "Välkommen till Screen Share Forge. Hjälp någon genom att se deras skärm live, utan att installera något." },
  "If you are the helper, press I want to help someone. You get a short code and a link to send.": { es: "Si eres quien ayuda, pulsa Quiero ayudar a alguien. Recibirás un código corto y un enlace para enviar.", ar: "إذا كنت المساعِد، فاضغط أريد مساعدة شخص ما. ستحصل على رمز قصير ورابط لإرساله.", zh: "如果你是帮忙的一方，按“我想帮助别人”。你会得到一个短码和一个可发送的链接。", sw: "Ikiwa wewe ndiye msaidizi, bonyeza Nataka kumsaidia mtu. Utapata msimbo mfupi na kiungo cha kutuma.", sv: "Om du är den som hjälper trycker du på Jag vill hjälpa någon. Du får en kort kod och en länk att skicka." },
  "The person who needs help opens the link, or presses the second button and types your code. Then they choose what to share: a window, a tab or the whole screen.": { es: "La persona que necesita ayuda abre el enlace o pulsa el segundo botón y escribe tu código. Luego elige qué compartir: una ventana, una pestaña o toda la pantalla.", ar: "يفتح الشخص الذي يحتاج المساعدة الرابط، أو يضغط الزر الثاني ويكتب رمزك. ثم يختار ما يشاركه: نافذة أو علامة تبويب أو الشاشة كاملة.", zh: "需要帮助的人打开链接，或者按第二个按钮并输入你的代码。然后选择要共享的内容：一个窗口、一个标签页或整个屏幕。", sw: "Mtu anayehitaji msaada hufungua kiungo, au hubonyeza kitufe cha pili na kuandika msimbo wako. Kisha huchagua cha kushiriki: dirisha, kichupo au skrini nzima.", sv: "Den som behöver hjälp öppnar länken, eller trycker på den andra knappen och skriver in din kod. Sedan väljer hen vad som ska delas: ett fönster, en flik eller hela skärmen." },
  "You see their screen live and can point at things. The video goes directly between the two browsers, and nothing is recorded unless you choose to.": { es: "Ves su pantalla en directo y puedes señalar cosas. El vídeo va directamente entre los dos navegadores y no se graba nada a menos que tú lo elijas.", ar: "ترى شاشته مباشرة ويمكنك الإشارة إلى الأشياء. ينتقل الفيديو مباشرة بين المتصفحين، ولا يُسجَّل شيء إلا إذا اخترت ذلك.", zh: "你能实时看到对方的屏幕，还能指向屏幕上的内容。视频直接在两个浏览器之间传输，除非你选择录制，否则不会录下任何内容。", sw: "Unaona skrini yake moja kwa moja na unaweza kuonyesha vitu. Video huenda moja kwa moja kati ya vivinjari viwili, na hakuna kinachorekodiwa isipokuwa ukichagua.", sv: "Du ser deras skärm live och kan peka på saker. Videon går direkt mellan de två webbläsarna, och inget spelas in om du inte väljer det." },
  "Now it is your turn. Open Screen Share Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Screen Share Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Screen Share Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Screen Share Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Screen Share Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Screen Share Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Screen Share Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Screen Share Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Screen Share Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Screen Share Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Screen Share Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Screen Share Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of David Hockney – click for more": { es: "Arte al estilo de David Hockney: haz clic para saber más", ar: "رسم بأسلوب ديفيد هوكني – انقر لمعرفة المزيد", zh: "大卫·霍克尼风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa David Hockney – bofya kujua zaidi", sv: "Konst i David Hockneys stil – klicka för mer" },
  "How to use Screen Share Forge": { es: "Cómo usar Screen Share Forge", ar: "كيفية استخدام Screen Share Forge", zh: "如何使用 Screen Share Forge", sw: "Jinsi ya kutumia Screen Share Forge", sv: "Så använder du Screen Share Forge" },
  "Screen Share Forge — help someone by watching their screen live": { es: "Screen Share Forge — ayuda a alguien viendo su pantalla en directo", ar: "Screen Share Forge — ساعد شخصًا بمشاهدة شاشته مباشرة", zh: "Screen Share Forge — 实时观看对方屏幕来帮助他们", sw: "Screen Share Forge — msaidie mtu kwa kutazama skrini yake moja kwa moja", sv: "Screen Share Forge — hjälp någon genom att se deras skärm live" }
});
