/* slide-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Italian Early Renaissance": { es: "Primer Renacimiento italiano", ar: "عصر النهضة الإيطالي المبكر", zh: "意大利早期文艺复兴", sw: "Mwamko wa mapema wa Kiitaliano", sv: "Italiensk tidigrenässans" },
  "A painter of the Medici court in Florence, loved for graceful, flowing figures in The Birth of Venus and Primavera.": { es: "Un pintor de la corte de los Médici en Florencia, apreciado por las figuras elegantes y fluidas de El nacimiento de Venus y La primavera.", ar: "رسام في بلاط آل ميديشي في فلورنسا، محبوب بشخصياته الرشيقة الانسيابية في \"مولد فينوس\" و\"الربيع\".", zh: "佛罗伦萨美第奇宫廷的画家，以《维纳斯的诞生》和《春》中优雅流畅的人物深受喜爱。", sw: "Mchoraji wa baraza la Medici huko Florence, anayependwa kwa wahusika wa kupendeza na wanaotiririka katika The Birth of Venus na Primavera.", sv: "En målare vid Medicihovet i Florens, älskad för de graciösa, flytande gestalterna i Venus födelse och Våren." },
  "The pale sea-green water, rippling waves and scallop shell recall The Birth of Venus. In front stands an original little sea monster drawn in the same colours, holding a bar chart that fits this tool.": { es: "El agua verde mar pálida, las olas onduladas y la concha de vieira recuerdan El nacimiento de Venus. Delante hay un pequeño monstruo marino original dibujado con los mismos colores, que sostiene un gráfico de barras acorde con esta herramienta.", ar: "المياه بلون أخضر البحر الباهت والأمواج المتموجة والصدفة المروحية تذكّر بلوحة \"مولد فينوس\". وفي المقدمة يقف وحش بحري صغير أصلي مرسوم بالألوان نفسها، يحمل مخططًا شريطيًا يناسب هذه الأداة.", zh: "淡海绿色的水面、粼粼波浪和扇贝壳，让人想起《维纳斯的诞生》。前方站着一只用同样颜色画成的原创小海怪，手里拿着一张与本工具相配的柱状图。", sw: "Maji ya rangi ya kijani-bahari hafifu, mawimbi yanayoviringika na gamba la kombe vinakumbusha The Birth of Venus. Mbele amesimama mnyama mdogo wa baharini halisi aliyechorwa kwa rangi zilezile, akishika chati ya pau inayolingana na zana hii.", sv: "Det blekt havsgröna vattnet, de krusande vågorna och pilgrimsmusslan påminner om Venus födelse. Framför står ett eget litet sjöodjur tecknat i samma färger, med ett stapeldiagram som passar det här verktyget." },
  "Watch how Slide Forge works — with voice": { es: "Mira cómo funciona Slide Forge, con voz", ar: "شاهد كيف يعمل Slide Forge — مع صوت", zh: "观看 Slide Forge 的使用方法（带语音）", sw: "Tazama jinsi Slide Forge inavyofanya kazi — kwa sauti", sv: "Se hur Slide Forge fungerar — med röst" },
  "Welcome to Slide Forge. Describe a presentation, and download it as a PowerPoint file.": { es: "Bienvenido a Slide Forge. Describe una presentación y descárgala como archivo de PowerPoint.", ar: "مرحبًا بك في Slide Forge. صِف عرضًا تقديميًا، ونزّله كملف PowerPoint.", zh: "欢迎使用 Slide Forge。描述一份演示文稿，然后下载为 PowerPoint 文件。", sw: "Karibu Slide Forge. Eleza wasilisho, na ulipakue kama faili la PowerPoint.", sv: "Välkommen till Slide Forge. Beskriv en presentation och ladda ner den som en PowerPoint-fil." },
  "Describe the presentation: the topic, the audience and the goal.": { es: "Describe la presentación: el tema, el público y el objetivo.", ar: "صِف العرض التقديمي: الموضوع والجمهور والهدف.", zh: "描述这份演示文稿：主题、受众和目标。", sw: "Eleza wasilisho: mada, hadhira na lengo.", sv: "Beskriv presentationen: ämnet, publiken och målet." },
  "Choose how many slides and a colour theme. Then press Plan slides with AI.": { es: "Elige cuántas diapositivas y un tema de color. Luego pulsa Planificar diapositivas con IA.", ar: "اختر عدد الشرائح وسمة ألوان. ثم اضغط خطّط الشرائح بالذكاء الاصطناعي.", zh: "选择幻灯片数量和配色主题。然后按“用 AI 规划幻灯片”。", sw: "Chagua idadi ya slaidi na mandhari ya rangi. Kisha bonyeza Panga slaidi kwa AI.", sv: "Välj hur många bilder och ett färgtema. Tryck sedan på Planera bilder med AI." },
  "Every slide appears here. Edit the titles and points, reorder them, or add photos.": { es: "Cada diapositiva aparece aquí. Edita los títulos y los puntos, cámbialas de orden o añade fotos.", ar: "تظهر كل شريحة هنا. عدّل العناوين والنقاط، أو أعد ترتيبها، أو أضف صورًا.", zh: "每张幻灯片都会显示在这里。编辑标题和要点、调整顺序，或添加照片。", sw: "Kila slaidi inaonekana hapa. Hariri vichwa na hoja, zipange upya, au ongeza picha.", sv: "Varje bild visas här. Redigera rubriker och punkter, ändra ordning eller lägg till foton." },
  "Press Build and download to get your PowerPoint file.": { es: "Pulsa Crear y descargar para obtener tu archivo de PowerPoint.", ar: "اضغط إنشاء وتنزيل للحصول على ملف PowerPoint.", zh: "按“生成并下载”获取你的 PowerPoint 文件。", sw: "Bonyeza Jenga na upakue kupata faili lako la PowerPoint.", sv: "Tryck på Bygg och ladda ner för att få din PowerPoint-fil." },
  "Now it is your turn. Open Slide Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Slide Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Slide Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Slide Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Slide Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Slide Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Slide Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Slide Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Slide Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Slide Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Slide Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Slide Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Sandro Botticelli – click for more": { es: "Arte al estilo de Sandro Botticelli: haz clic para saber más", ar: "رسم بأسلوب ساندرو بوتيتشيلي – انقر لمعرفة المزيد", zh: "桑德罗·波提切利风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Sandro Botticelli – bofya kujua zaidi", sv: "Konst i Sandro Botticellis stil – klicka för mer" },
  "e.g. A pitch deck for a plumbing business: intro, the problem, our services, why us, pricing, contact": { es: "p. ej. Una presentación para una empresa de fontanería: introducción, el problema, nuestros servicios, por qué nosotros, precios, contacto", ar: "مثلًا: عرض تقديمي لشركة سباكة: مقدمة، المشكلة، خدماتنا، لماذا نحن، الأسعار، التواصل", zh: "例如：一家水管公司的路演 PPT：简介、问题、我们的服务、为什么选我们、价格、联系方式", sw: "k.m. Wasilisho la biashara ya mabomba: utangulizi, tatizo, huduma zetu, kwa nini sisi, bei, mawasiliano", sv: "t.ex. En pitch för ett rörfirma: intro, problemet, våra tjänster, varför oss, priser, kontakt" },
  "Let the AI decide (4–10)": { es: "Que decida la IA (4–10)", ar: "دع الذكاء الاصطناعي يقرر (4–10)", zh: "让 AI 决定（4–10）", sw: "Acha AI iamue (4–10)", sv: "Låt AI:n bestämma (4–10)" },
  "How to use Slide Forge": { es: "Cómo usar Slide Forge", ar: "كيفية استخدام Slide Forge", zh: "如何使用 Slide Forge", sw: "Jinsi ya kutumia Slide Forge", sv: "Så använder du Slide Forge" },
  "Slide Forge — free PowerPoint generator": { es: "Slide Forge — generador de PowerPoint gratis", ar: "Slide Forge — منشئ عروض PowerPoint مجاني", zh: "Slide Forge — 免费 PowerPoint 生成器", sw: "Slide Forge — kitengeneza PowerPoint cha bure", sv: "Slide Forge — gratis PowerPoint-generator" }
});
