/* talk-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Mannerism": { es: "Manierismo", ar: "التكلّفية (المانييرية)", zh: "风格主义", sw: "Umanerisimu", sv: "Manierism" },
  "A Greek-born painter who worked in Toledo, Spain, known for stretched, flickering figures and stormy skies, as in View of Toledo.": { es: "Un pintor nacido en Grecia que trabajó en Toledo, España, conocido por sus figuras alargadas y vibrantes y sus cielos tormentosos, como en Vista de Toledo.", ar: "رسام يوناني المولد عمل في طليطلة بإسبانيا، اشتهر بشخصياته الممدودة المرتعشة وسمائه العاصفة، كما في لوحة \"منظر طليطلة\".", zh: "一位出生于希腊、在西班牙托莱多工作的画家，以拉长、闪烁的人物和暴风雨般的天空闻名，如《托莱多风景》。", sw: "Mchoraji mzaliwa wa Ugiriki aliyefanya kazi Toledo, Uhispania, anayejulikana kwa wahusika waliorefushwa wanaometameta na anga zenye dhoruba, kama katika View of Toledo.", sv: "En grekfödd målare som verkade i Toledo i Spanien, känd för utdragna, fladdrande gestalter och stormiga himlar, som i Vy över Toledo." },
  "Tall, wavering strokes of green and white over a jagged skyline recall his View of Toledo. In front stands an original bat drawn in the same colours, holding a speech bubble that fits this tool.": { es: "Trazos altos y ondulantes en verde y blanco sobre un horizonte irregular recuerdan su Vista de Toledo. Delante hay un murciélago original dibujado con los mismos colores, que sostiene un bocadillo de diálogo acorde con esta herramienta.", ar: "ضربات فرشاة طويلة متموجة بالأخضر والأبيض فوق أفق مسنّن تذكّر بلوحته \"منظر طليطلة\". وفي المقدمة يقف خفاش أصلي مرسوم بالألوان نفسها، يحمل فقاعة كلام تناسب هذه الأداة.", zh: "参差天际线上方高耸摇曳的绿白笔触，让人想起他的《托莱多风景》。前方站着一只用同样颜色画成的原创蝙蝠，手里拿着一个与本工具相配的对话气泡。", sw: "Mistari mirefu inayoyumba ya kijani na nyeupe juu ya upeo wa macho uliochongoka inakumbusha View of Toledo yake. Mbele amesimama popo halisi aliyechorwa kwa rangi zilezile, akishika kiputo cha maneno kinacholingana na zana hii.", sv: "Höga, vacklande drag i grönt och vitt över en taggig silhuett påminner om hans Vy över Toledo. Framför står en egen fladdermus tecknad i samma färger, med en pratbubbla som passar det här verktyget." },
  "No photo": { es: "Sin foto", ar: "بلا صورة", zh: "无照片", sw: "Hakuna picha", sv: "Inget foto" },
  "Off-screen narrator": { es: "Narrador fuera de pantalla", ar: "راوٍ من خارج الشاشة", zh: "画外旁白", sw: "Msimulizi asiyeonekana", sv: "Berättare utanför bild" },
  "Watch how Talk Forge works — with voice": { es: "Mira cómo funciona Talk Forge, con voz", ar: "شاهد كيف يعمل Talk Forge — مع صوت", zh: "观看 Talk Forge 的使用方法（带语音）", sw: "Tazama jinsi Talk Forge inavyofanya kazi — kwa sauti", sv: "Se hur Talk Forge fungerar — med röst" },
  "Welcome to Talk Forge. Make a photo speak, with moving lips.": { es: "Bienvenido a Talk Forge. Haz que una foto hable, moviendo los labios.", ar: "مرحبًا بك في Talk Forge. اجعل صورة تتكلم بشفاه متحركة.", zh: "欢迎使用 Talk Forge。让照片开口说话，嘴唇还会动。", sw: "Karibu Talk Forge. Fanya picha iongee, kwa midomo inayosonga.", sv: "Välkommen till Talk Forge. Få ett foto att prata, med läppar som rör sig." },
  "Add a photo. Faces are found automatically, or you can place a face yourself.": { es: "Añade una foto. Las caras se detectan automáticamente, o puedes colocar una cara tú mismo.", ar: "أضف صورة. تُكتشف الوجوه تلقائيًا، أو يمكنك تحديد الوجه بنفسك.", zh: "添加一张照片。系统会自动找到人脸，你也可以自己标出人脸。", sw: "Ongeza picha. Nyuso hupatikana kiotomatiki, au unaweza kuweka uso mwenyewe.", sv: "Lägg till ett foto. Ansikten hittas automatiskt, eller så placerar du ett ansikte själv." },
  "Here we place it by hand: press Place manually, then click the left eye, the right eye and the mouth.": { es: "Aquí la colocamos a mano: pulsa Colocar manualmente y luego haz clic en el ojo izquierdo, el ojo derecho y la boca.", ar: "هنا نحدده يدويًا: اضغط تحديد يدوي، ثم انقر على العين اليسرى والعين اليمنى والفم.", zh: "这里我们手动标出：按“手动放置”，然后依次点击左眼、右眼和嘴巴。", sw: "Hapa tunauweka kwa mkono: bonyeza Weka kwa mkono, kisha bofya jicho la kushoto, jicho la kulia na mdomo.", sv: "Här placerar vi det för hand: tryck på Placera manuellt och klicka sedan på vänster öga, höger öga och munnen." },
  "Choose who says the line, then type what they say, or record your own voice.": { es: "Elige quién dice la frase y luego escribe lo que dice, o graba tu propia voz.", ar: "اختر من يقول الجملة، ثم اكتب ما يقوله، أو سجّل صوتك.", zh: "选择由谁说这句台词，然后输入台词内容，或者录下你自己的声音。", sw: "Chagua nani anasema mstari huo, kisha andika anachosema, au rekodi sauti yako mwenyewe.", sv: "Välj vem som säger repliken, skriv sedan vad hen säger eller spela in din egen röst." },
  "Pick a voice, and press Preview to watch the lips move.": { es: "Elige una voz y pulsa Vista previa para ver cómo se mueven los labios.", ar: "اختر صوتًا، واضغط معاينة لترى الشفاه تتحرك.", zh: "选择一个声音，按“预览”看嘴唇动起来。", sw: "Chagua sauti, na ubonyeze Hakiki kutazama midomo ikisonga.", sv: "Välj en röst och tryck på Förhandsgranska för att se läpparna röra sig." },
  "When you are happy, record it and download the video.": { es: "Cuando estés satisfecho, grábalo y descarga el vídeo.", ar: "عندما تكون راضيًا، سجّله ونزّل الفيديو.", zh: "满意后，录制并下载视频。", sw: "Ukiridhika, irekodi na upakue video.", sv: "När du är nöjd spelar du in den och laddar ner videon." },
  "Now it is your turn. Open Talk Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Talk Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Talk Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Talk Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Talk Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Talk Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Talk Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Talk Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Talk Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Talk Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Talk Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Talk Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of El Greco – click for more": { es: "Arte al estilo de El Greco: haz clic para saber más", ar: "رسم بأسلوب إل غريكو – انقر لمعرفة المزيد", zh: "埃尔·格列柯风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa El Greco – bofya kujua zaidi", sv: "Konst i El Grecos stil – klicka för mer" },
  "Photo for this line": { es: "Foto para esta frase", ar: "صورة لهذه الجملة", zh: "这句台词的照片", sw: "Picha ya mstari huu", sv: "Foto för den här repliken" },
  "Who says this line": { es: "Quién dice esta frase", ar: "من يقول هذه الجملة", zh: "谁说这句台词", sw: "Nani anasema mstari huu", sv: "Vem som säger repliken" },
  "What they say…": { es: "Lo que dicen…", ar: "ما يقولونه…", zh: "对方说的话…", sw: "Wanachosema…", sv: "Vad de säger…" },
  "How to use Talk Forge": { es: "Cómo usar Talk Forge", ar: "كيفية استخدام Talk Forge", zh: "如何使用 Talk Forge", sw: "Jinsi ya kutumia Talk Forge", sv: "Så använder du Talk Forge" },
  "Talk Forge — make a photo talk from a script": { es: "Talk Forge — haz que una foto hable a partir de un guion", ar: "Talk Forge — اجعل صورة تتكلم من نص مكتوب", zh: "Talk Forge — 根据脚本让照片说话", sw: "Talk Forge — fanya picha iongee kutoka kwa hati", sv: "Talk Forge — få ett foto att prata utifrån ett manus" }
});
