/* video-forge.html — translations of this page's text, matched by the English original (see i18n.js). */
I18N.phrases({
  "Baroque (tenebrism)": { es: "Barroco (tenebrismo)", ar: "الباروك (التينبريزم)", zh: "巴洛克（暗色调主义）", sw: "Baroki (tenebrism)", sv: "Barock (tenebrism)" },
  "An Italian painter of dramatic realism who lit figures with a single hard beam of light against deep darkness.": { es: "Un pintor italiano de realismo dramático que iluminaba a sus figuras con un único haz de luz intenso contra una oscuridad profunda.", ar: "رسام إيطالي من أصحاب الواقعية الدرامية، كان يضيء شخصياته بشعاع ضوء واحد حاد وسط ظلام دامس.", zh: "一位意大利戏剧性写实主义画家，用一道强烈的光束在深沉的黑暗中照亮人物。", sw: "Mchoraji wa Kiitaliano wa uhalisia wa kuigiza aliyeangaza wahusika kwa mwale mmoja mkali wa mwanga dhidi ya giza nene.", sv: "En italiensk målare av dramatisk realism som belyste gestalterna med en enda hård ljusstråle mot djupt mörker." },
  "A near-black room cut by one diagonal shaft of warm light is his trademark chiaroscuro. In front stands an original dragon drawn in the same colours, holding a film clapperboard that fits this tool.": { es: "Una habitación casi negra atravesada por un solo rayo diagonal de luz cálida es su característico claroscuro. Delante hay un dragón original dibujado con los mismos colores, que sostiene una claqueta de cine acorde con esta herramienta.", ar: "غرفة شبه سوداء يشقّها شعاع مائل واحد من الضوء الدافئ، وهذا هو أسلوبه المميز في الضوء والظل (الكياروسكورو). وفي المقدمة يقف تنين أصلي مرسوم بالألوان نفسها، يحمل لوح تصوير سينمائي يناسب هذه الأداة.", zh: "一间几近全黑的房间被一道斜射的暖光划破，这正是他标志性的明暗对照法。前方站着一条用同样颜色画成的原创龙，手里拿着一块与本工具相配的电影场记板。", sw: "Chumba karibu cheusi kilichokatwa na mwale mmoja wa mshazari wa mwanga wa joto ndio chiaroscuro yake maarufu. Mbele amesimama joka halisi aliyechorwa kwa rangi zilezile, akishika ubao wa kurekodi filamu unaolingana na zana hii.", sv: "Ett nästan svart rum genomskuret av en enda diagonal stråle varmt ljus är hans kännetecknande chiaroscuro. Framför står en egen drake tecknad i samma färger, med en filmklappa som passar det här verktyget." },
  "Each drawing slowly pans and zooms for a cinematic feel.": { es: "Cada dibujo se desplaza y se acerca lentamente para dar un toque cinematográfico.", ar: "تتحرك كل رسمة وتقترب ببطء لإحساس سينمائي.", zh: "每幅画都会缓慢平移和缩放，营造电影感。", sw: "Kila mchoro husogea na kukuzwa polepole ili kuleta hisia ya kisinema.", sv: "Varje teckning panoreras och zoomas långsamt för en filmisk känsla." },
  "Watch how Video Forge works — with voice": { es: "Mira cómo funciona Video Forge, con voz", ar: "شاهد كيف يعمل Video Forge — مع صوت", zh: "观看 Video Forge 的使用方法（带语音）", sw: "Tazama jinsi Video Forge inavyofanya kazi — kwa sauti", sv: "Se hur Video Forge fungerar — med röst" },
  "Welcome to Video Forge. Turn drawings and pictures into a moving video.": { es: "Bienvenido a Video Forge. Convierte dibujos e imágenes en un vídeo en movimiento.", ar: "مرحبًا بك في Video Forge. حوّل الرسومات والصور إلى فيديو متحرك.", zh: "欢迎使用 Video Forge。把画作和图片变成动起来的视频。", sw: "Karibu Video Forge. Geuza michoro na picha kuwa video inayosonga.", sv: "Välkommen till Video Forge. Gör teckningar och bilder till en rörlig video." },
  "Add drawings, photos or scans, in the order they should appear.": { es: "Añade dibujos, fotos o escaneos en el orden en que deben aparecer.", ar: "أضف رسومات أو صورًا أو مستندات ممسوحة، بالترتيب الذي يجب أن تظهر به.", zh: "按出现顺序添加画作、照片或扫描件。", sw: "Ongeza michoro, picha au nakala zilizochanganuliwa, kwa mpangilio zinavyopaswa kuonekana.", sv: "Lägg till teckningar, foton eller skanningar i den ordning de ska visas." },
  "Choose how they move: a slow zoom, quick cuts, or a flipbook. Then choose a transition.": { es: "Elige cómo se mueven: un zoom lento, cortes rápidos o un flipbook. Luego elige una transición.", ar: "اختر طريقة حركتها: تكبير بطيء، أو قطع سريع، أو كتاب متحرك. ثم اختر انتقالًا.", zh: "选择它们的动态方式：缓慢缩放、快速切换或手翻书。然后选择一种转场。", sw: "Chagua jinsi zinavyosonga: kukuza polepole, mikato ya haraka, au kitabu cha kugeuza. Kisha chagua mpito.", sv: "Välj hur de rör sig: en långsam zoom, snabba klipp eller en blädderbok. Välj sedan en övergång." },
  "Add a title, captions and music if you like, then press Render video.": { es: "Añade un título, subtítulos y música si quieres, y luego pulsa Renderizar vídeo.", ar: "أضف عنوانًا وتعليقات وموسيقى إن أردت، ثم اضغط تصيير الفيديو.", zh: "如果愿意，可以添加标题、字幕和音乐，然后按“渲染视频”。", sw: "Ongeza kichwa, maelezo na muziki ukipenda, kisha bonyeza Tengeneza video.", sv: "Lägg till en titel, textning och musik om du vill och tryck sedan på Rendera video." },
  "Preview it, and download the video.": { es: "Previsualízalo y descarga el vídeo.", ar: "عاينه، ثم نزّل الفيديو.", zh: "预览一下，然后下载视频。", sw: "Ihakiki, na upakue video.", sv: "Förhandsgranska den och ladda ner videon." },
  "Now it is your turn. Open Video Forge on MigaBuilder and try it yourself. It is free, and there is nothing to sign up for.": { es: "Ahora te toca a ti. Abre Video Forge en MigaBuilder y pruébalo. Es gratis y no hace falta registrarse.", ar: "الآن جاء دورك. افتح Video Forge على MigaBuilder وجرّبه بنفسك. إنه مجاني ولا يحتاج إلى تسجيل.", zh: "现在轮到你了。在 MigaBuilder 上打开 Video Forge 亲自试试。它是免费的，无需注册。", sw: "Sasa ni zamu yako. Fungua Video Forge kwenye MigaBuilder ujaribu mwenyewe. Ni bure, na hakuna haja ya kujisajili.", sv: "Nu är det din tur. Öppna Video Forge på MigaBuilder och prova själv. Det är gratis och du behöver inte registrera dig." },
  "Welcome to Video Forge. This walkthrough uses the real tool controls on this page.": { es: "Bienvenido a Video Forge. Este recorrido usa los controles reales de la herramienta en esta página.", ar: "مرحبًا بك في Video Forge. تستخدم هذه الجولة عناصر التحكم الحقيقية للأداة على هذه الصفحة.", zh: "欢迎使用 Video Forge。本演示使用本页上真实的工具控件。", sw: "Karibu Video Forge. Mwongozo huu unatumia vidhibiti halisi vya zana kwenye ukurasa huu.", sv: "Välkommen till Video Forge. Genomgången använder verktygets riktiga kontroller på den här sidan." },
  "Art in the style of Caravaggio – click for more": { es: "Arte al estilo de Caravaggio: haz clic para saber más", ar: "رسم بأسلوب كارافاجو – انقر لمعرفة المزيد", zh: "卡拉瓦乔风格的插画——点击了解更多", sw: "Sanaa kwa mtindo wa Caravaggio – bofya kujua zaidi", sv: "Konst i Caravaggios stil – klicka för mer" },
  "e.g. My Dragon Adventure": { es: "p. ej., Mi aventura con el dragón", ar: "مثلًا: مغامرتي مع التنين", zh: "例如：我的飞龙冒险", sw: "k.m. Safari Yangu ya Joka", sv: "t.ex. Mitt drakäventyr" },
  "e.g. Drawn by Alex, age 8": { es: "p. ej., Dibujado por Alex, 8 años", ar: "مثلًا: رسمه أليكس، 8 سنوات", zh: "例如：Alex 绘，8 岁", sw: "k.m. Imechorwa na Alex, miaka 8", sv: "t.ex. Ritad av Alex, 8 år" },
  "e.g. Believe in yourself": { es: "p. ej., Cree en ti", ar: "مثلًا: آمن بنفسك", zh: "例如：相信你自己", sw: "k.m. Jiamini", sv: "t.ex. Tro på dig själv" },
  "My Dragon Adventure": { es: "Mi aventura con el dragón", ar: "مغامرتي مع التنين", zh: "我的飞龙冒险", sw: "Safari Yangu ya Joka", sv: "Mitt drakäventyr" },
  "Made with Video Forge from my own drawings.": { es: "Hecho con Video Forge a partir de mis propios dibujos.", ar: "صُنع باستخدام Video Forge من رسوماتي الخاصة.", zh: "用 Video Forge 根据我自己的画作制作。", sw: "Imetengenezwa kwa Video Forge kutokana na michoro yangu mwenyewe.", sv: "Gjord med Video Forge av mina egna teckningar." },
  "drawing, animation, kids art": { es: "dibujo, animación, arte infantil", ar: "رسم، رسوم متحركة، فن الأطفال", zh: "绘画, 动画, 儿童艺术", sw: "mchoro, uhuishaji, sanaa ya watoto", sv: "teckning, animation, barnkonst" },
  "How to use Video Forge": { es: "Cómo usar Video Forge", ar: "كيفية استخدام Video Forge", zh: "如何使用 Video Forge", sw: "Jinsi ya kutumia Video Forge", sv: "Så använder du Video Forge" },
  "Video Forge — turn your drawings into a video, ready for YouTube": { es: "Video Forge — convierte tus dibujos en un vídeo listo para YouTube", ar: "Video Forge — حوّل رسوماتك إلى فيديو جاهز لـ YouTube", zh: "Video Forge — 把你的画作变成视频，可直接发布到 YouTube", sw: "Video Forge — geuza michoro yako kuwa video, tayari kwa YouTube", sv: "Video Forge — gör dina teckningar till en video, redo för YouTube" }
});
